### ISSUE TITLE
文教会館の調査結果を記録に残す

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#1006]
https://github.com/kanazawarb/meetup/wiki/%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E9%96%8B%E5%82%AC%E5%A0%B4%E6%89%80%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%83%AA%E3%82%B9%E3%83%88

上記を参照にご対応ください。 @wtnabe

**Comment by wtnabe** [comment]
:raised_hands:
