### ISSUE TITLE
textile から markdown に移行しませんか

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#108]
大変アレがナニなので。
コンバーターとか無いのかしら。
テンプレートと依存関係あるの？ > @wtnabe

**Comment by PharaohKJ** [comment]
#545 において、私の手元で jekyll が textile を処理してくれなくて憤慨して md で作っちゃいました。てへぺろ〜。

誰か手元でブランチで bundle exec rake serve し、

- [ ] 1. `/42/`のmdが変換されててまともに見られること確認し
- [ ] 2. それ以外のtextileもちゃんと変換されててまともに見られること確認し(index.htmlと/41/だけみればいいかと)

gh-pagesにマージ後
- [ ] 3. 本番ページがまともにみられる

のを確認したら以降、それを使うってことでここcloseできるんじゃないかなー？どうでしょ？

そういうわけで、どなたか1. 2. 確認お願いします。 >  @kanazawarb/owners 
3. は `/42/` 公開後、私がやってここcloseします。

**Comment by PharaohKJ** [comment]
いつも更新してくれている @cottondesu 先生わるいけど 1. 2. やってみてくれない？

**Comment by cottondesu** [comment]
以下の状態で動作確認しました。

$ git status
HEAD detached at origin/add_meetup42
nothing to commit, working directory clean
$ git log --oneline
75055d5 Update for meetup42 with markdown.
f6ec27e Update index.textile
91e4daa Update index.textile
a7c6fe8 add:meetup 42
....
....
$ bundle exec rake serve

結果はOKです。
meetup42(md)のページはちゃんと見れてます。
meetup41(textile)のページもちゃんと見れてます。

質問に対しての返答から少しそれますが、meetup42のITプラザ武蔵の
リンク表示の仕方が今までとちょっと違う感じですかね。
好みの問題かなと思います。

画面のスクリーンショットはidobataに貼っておきますので
判断お願いします。

**Comment by PharaohKJ** [comment]
確認しました。うーん。なぜかわからないですが、とりま、うまくいっているようでしたら
いったんこれでOKにしましょう。

そしてこのissue閉じます。ok? @wtnabe どの。okなら閉じちゃってください。

**Comment by wtnabe** [comment]
:+1:
