### ISSUE TITLE
meetup93 LT title list

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#1140]
2020/05/16 に開催される meetup 93 LT 大会に向けて、事前に LT の内容を共有するための Issue です。
運営を円滑にすることと、まだ発表ネタを考えている途中の人へのフォローアップとして活用させていただきます。

* **ご協力いただける方にお願いするものです**
    書き込みをしないと meetup に参加できないといったものでは **ありません**

* 事前に共有できる方は、発表の **タイトル** を書き込んでください。
    タイトルは内容を類推するために共有いただくものですので、確定でなくても結構です。
    発表時に変更していただいても大丈夫です。

* プラスアルファ、お名前も添えていただけると、さらに助かります。
    お名前は、イベントページのタイムラインに記載します（指定なければ記載しません）

* 複数の発表を考えている方は、何個書き込んでいただいてもかまいません。

**Comment by kiyohara** [comment]
タイトル : Alfred Workflow をつくろう
名前: kiyohara

**Comment by izawa** [comment]
タイトル : 災害グッズとして見たときのキャンプ道具選び
名前: izawa

**Comment by TAKAyukiatkwsk** [comment]
タイトル: 私が知っておきたかった統計手法(仮)
名前: takayukiatkwsk

**Comment by kotaronov27** [comment]
タイトル：リモートワークことはじめ
名前：YagiKotaro

**Comment by cottondesu** [comment]
タイトル：Circle CI 1.0からGitHub Actionsに乗りカエル
名前：cottondesu

**Comment by RyuseiNomi** [comment]
タイトル：iOSアプリをリリースするまで
名前：Tonto

**Comment by RyuseiNomi** [comment]
タイトル：AWS Lambdaでファイルをこねくり回す
名前：tonto

**Comment by kentaro-m** [comment]
タイトル：実践スナップショットテスト 〜UIのあるべき姿を担保するために〜
名前：matsuken

**Comment by issekiamp** [comment]
タイトル：THETAシリーズ用シャッターリモコンの作製
名前：issekiamp

**Comment by satoru-takeuchi** [comment]
タイトル: container runtimes
名前: sat

**Comment by kiyohara** [comment]
運営がとてもスムーズに行えました！ご協力ありがとうございました！ 🙇
