### ISSUE TITLE
pull pnada migration

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#1162]
Github から migrate してねというメールがきているのでどこかで対応する。
8月14日までには対応した方がよさそう。

---

> Since we [announced the acquisition](https://github.blog/2019-06-17-github-acquires-pull-panda/) of Pull Panda last year, we’ve been working hard to bring its features into your GitHub experience. Now, Pull Assigner and Pull Reminders are available on GitHub as [code review assignment](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team) and [scheduled reminders](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-team).
> 
> As we now have a GitHub-native experience, both **Pull Assigner and Pull Reminders will no longer operate as of October 14, 2020.** You’ll find migration steps below to make the transition to code review assignments and scheduled reminders. 
> 
> Note, Pull Analytics will continue operating as it does today.
> 
> Next steps
> 
> * If you’re using Pull Assigner, learn more about how to configure and use [code review assignments](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-code-review-assignment-for-your-team).
> * If you’re using Pull Reminders, a migrate option will appear on pull reminder notifications in Slack once your organization is connected to a Slack workspace (see [steps](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-organization)). Most personal and channel reminder settings will migrate without any additional action, but in some cases, you may need to answer questions or adjust some settings. You’ll be guided through the process step by step. Learn more about [team reminders](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-scheduled-reminders-for-your-team) and [personal reminders](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-scheduled-reminders).

**Comment by kiyohara** [comment]
7/21 あたりでおおよそ対応したはずなのだけど、 Pull Panda の設定が残ってしまっている様子。
8/4 に追加の施策をしてみたので、しばらく様子を見る。
slack の `#github` に Pull Panda からの daily notification が来なくなったら完了。
ただ、放っておいても 8/14 には勝手に破棄されるのでは、という気もしている。

**Comment by TAKAyukiatkwsk** [comment]
@kiyohara これはもう移行済みって感じですかね？？pull pandaからの通知は来なくなった気はします。

**Comment by kiyohara** [comment]
@TAKAyukiatkwsk ですね！クローズしてよさそうー。
リマインド感謝です！！ 💪
