### ISSUE TITLE
github pages作成のワークフロー変更

### ISSUE THREAD

**Issue by wtnabe** [kanazawarb/meetup#119]
link の自動生成の続きです。pull-req って reopen できないんですね。当たり前っちゃ当たり前か。

とりあえず以下の branch
- feature/deploy-automation
- gh-pages-test

を push しました。できることは
- feature/deploy-automation 上で内容の編集と commit
- これでよければ `rake deploy` で jekyll build した成果を所定の branch（現在は gh-pages-test）に push する

です。これで大丈夫ということであればそれぞれを
- master
- gh-pages

に置き換えて運用しようかと思うのですが、どうでしょうか。

これで unsafe な plugin である collection tag を使って link の埋め込みを自動化しつつ、github pages 上で build できないという問題を解決できます。ただし、大きなインパクトとしては
- ワークフローが変わる

ことが挙げられます。
1. 従来のように gh-pages だけいじって push では済まない
2. Webから master を修正するだけではダメだし、まして gh-pages をいじっちゃうと master と乖離する

従って、

**master で作業して `rake deploy` を新しいワークフローとして採用する**

という形になります。

ふー説明を簡略化するためにまともに動く状態まで持って来るだけで疲れた。

cf.

[俺の最強ブログシステムも火を噴いてたぜ - Webtech Walker](http://webtech-walker.com/archive/2012/09/fired-myblog.html)

上記の参照先の通りだとうまく branch をまたげないんですが、用意した Rakefile は branch をまたいで静的サイトになった成果物を push できるはずです。

**Comment by PharaohKJ** [comment]
もうとじてくよね？これ。どうでしょ？ @wtnabe

**Comment by kiyohara** [comment]
本件、 Netlify に移行した（つまり、プレビューを閲覧できる状況になった）ことを鑑みクローズする。
PR にする前に、手元で確認するためのドキュメントは必要かもしれない。それはそれ、別の Issue との認識。
