### ISSUE TITLE
meetup 110 イベントコラボ

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#1236]
meetup 108の懇親会で少し相談しましたが、私の友人からイベントコラボしませんかと
お誘いを受けました。meetup 110 (10月)をコラボ開催できるように調整していきます。

「みんなのCSIRT」っていう勉強会なのですが、ホームページないです。

内容は以下の本の著者による本の解説です。
たぶんWeb関連の内容多めになると思われます。

詳解セキュリティコンテスト
https://www.amazon.co.jp/%E8%A9%B3%E8%A7%A3%E3%82%BB%E3%82%AD%E3%83%A5%E3%83%AA%E3%83%86%E3%82%A3%E3%82%B3%E3%83%B3%E3%83%86%E3%82%B9%E3%83%88-%E6%A2%85%E5%86%85%E7%BF%BC-ebook/dp/B094J7ZCJN

当初meetup 110は2021/10/16(Sat)開催の予定でしたが、先方の都合により
第四土曜日の2021/10/23(Sat)になりました。事後報告になってすいません。
開始時間は通常通り13:00開場、13:15開始で問題ないです。

どんな感じで開催するかは明日友人と話すので決まった内容を共有します。

**Comment by cottondesu** [comment]
先日「みんなのCSIRT」主催者と会話した内容を情報共有します。

* zoomのURLは kanazawa.rb で発行する。
* イベント用のdoorkeeperは kanazawa.rb で作成する。
* 詳解セキュリティコンテスト著者でWeb関連を
  担当した梅内翼さんは以下のような人です。

https://www.amazon.co.jp/%E6%A2%85%E5%86%85%E7%BF%BC/e/B094JZ4WWR/
https://sz4rny.notion.site/sz4rny/Resume-92e9a307bd414346938a9c6a4c2acdc6

大枠の時間割は以下の通りです。
コミュニティの紹介の場所が変わったりするかもしませんが
だいたいこんな感じです。

| 13:15-13:30  | 自己紹介 |
|13:30-14:30  | 梅内翼さん解説＋ハンズオン |
|14:30-14:40  | 休憩 |
|14:40-14:55  | 各コミュニティの紹介 |
|14:55-15:10  | 各コミュニティの紹介 |
|15:10-15:55  | サイドチャネル攻撃のハンズオン＋解説 |
|15:55-16:05 | 休憩 |
|16:05-16:50 | 他のハンズオン＋解説 or ディスカッション |

最初のハンズオン以外は「みんなのCSIRT」主催者が行う予定です。


9/1(水)19:00に梅原さんを交えて打ち合わせがあります。
打ち合わせ参加できるよって人がいましたら手をあげてくれると
個別でmeetのURLをお伝えします。

その打ち合わせでもしかしたら、kanazawa.rb で
開発でセキュリティに気をつけていることは？
kanazawa.rb 側でも何か話してくれるとうれしいなって感じになるかもしません。

打ち合わせ後に情報共有します。

**Comment by cottondesu** [comment]
9/1の打ち合わせ内容を共有します。
時間割を以下のように修正しました。

|13:15-13:30 | 自己紹介 |
|13:30-13:45 | kanazawa.rb コミュニティの紹介 |
|13:45-14:00 | みんなのCSIRT コミュニティの紹介 |
|14:00-15:00 | 梅内翼さん解説＋ハンズオン |
|15:00-15:10 | 休憩 |
|15:10-15:55 | サイドチャネル攻撃のハンズオン＋解説 |
|15:55-16:05 | 休憩 |
|16:05-16:50 | ディスカッション |

変更点はコミュニティ紹介を自己紹介後に移動し、
16:05以降の内容をディスカッションに変更しました。

ディスカッションテーマ
  1. 普段の開発体制や開発で気をつけていること
  2. インシデント後の対応手順はあるのか？ (時間があれば)

1.はセキュリティに関連してなくてもいいとのことです。

不明点や聞きたいこと、めっちゃ話したいとかあれば言ってください。

**Comment by TAKAyukiatkwsk** [comment]
meetup109内での打ち合わせメモ

サイドチャネル攻撃のハンズオンについて参加者が事前に準備するものは特になしとのことだった。（WebブラウザがあればOK）
梅内さんハンズオンについては本人に確認しないと分からないとのことだったので、分かり次第小西さんから展開していただく。

**Comment by TAKAyukiatkwsk** [comment]
無事終了したのでクローズ
