### ISSUE TITLE
コミュニティ資金の確認

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#1242]
来月か再来月のレポートページの収支を
更新したいので、現在のコミュニティ資金を確認したいです。

私が把握している金額は、9,292円です

@kiyohara さん
SUZURI 上にドネーション金額14,000円、
振込金額を差し引いた金額を銀振して
doorkeeper費(2021/7-12)6ヶ月(9,900円)を
引いた金額・明細を教えてください。

お金をどこで一括管理するかは別の機会にお話ししましょう。

**Comment by kiyohara** [comment]
@cottondesu 対応ありがとうございます。

SUZURI 上にある送金可能な金額は今時点（2021/09/21）で19,000円です。
認識してもらっているとおり、申請することで、振込手数料を引かれた上で指定口座に振り込んでもらうことが出来ます。
記念回も終了しましたし、運用メンバーリフレッシュのタイミングも迎えたので一度振込申請してみますね。
手数料引かれた上でいくら取得できるか、また連絡します。

doorkeeper 費用は、想定してもらっているとおり月次1,650円かかっています。
現状 7,8,9月の三ヶ月分を立て替えている形になります。

<img width="694" alt="スクリーンショット 2021-09-21 15 06 51" src="https://user-images.githubusercontent.com/340621/134120095-5cc93d25-d730-41ef-a1a2-155872821326.png">

**Comment by kiyohara** [comment]
@cottondesu 申請したところ「見通し」が即時に表示されました。
手数料176円で、振込額18,824円だそうです。

<img width="701" alt="スクリーンショット 2021-09-21 15 07 50" src="https://user-images.githubusercontent.com/340621/134120189-6931ca65-5f3c-41c9-88f6-0f1f57d383a2.png">

取り急ぎ情報共有まで。
10月29日に振込予定となっているので、最終的な確認がとれたらまた連絡します。

**Comment by cottondesu** [comment]
@kiyohara さん
わかりました。連絡をお待ちしてます。
doorkeeper代の10月、11月、12月分は支払予定分として加味し
doorkeeper費(2021/7-12)6ヶ月(9,900円)として先に引いても大丈夫です。

台帳で把握して実際の金額と一致すれば問題ないです。

**Comment by kiyohara** [comment]
@cottondesu 10月末のタイミングで、上述の通り 18,824円が私の口座に振り込まれているのを確認しました。
doorkeeper費(2021/7-12)6ヶ月(9,900円) を除くと、8,924円となるかと思います。

なんらかの方法で、 @cottondesu さんに 8,924円 を渡せればと思うのですが、よい手はありますかね？
Amazon ギフトカードとかで送れるなら、（その分の現金を @cottondesu 先生が kzrb 財布に入れる手間を許容してもらえるなら）アマギフコードを送付します。どうでしょう。
本当は直接現金を持って会いに行ければよいのでしょうが… 他によい手があれば是非コメントくださいー 💪

**Comment by cottondesu** [comment]
@kiyohara 
私はAmazonギフトカードでも大丈夫です。

もしくは当面はオフラインでの開催はないと思うので出費は毎月のdoorkeeper費のみとなります。
逆転の発想で私が管理している金額(9,292円)を @kiyohara さんに渡す案もあると思うのですが
どうでしょうか？

**Comment by kiyohara** [comment]
@cottondesu なるほど、事実上 Doorkeeper とドメイン費用ぐらいですからね。
いずれも私が支払いしてますし、私が管理した方が話が早いのか… も？
うーん、どうしようかな。
キャッシュフロー管理は Dropbox 上の numbers がマスターとの認識で正しいですか？

**Comment by cottondesu** [comment]
@kiyohara Dropbox 上の numbers がマスターです。
2021年11月として収入(18,824円)とdoorkeeper費(2021/7-12)6ヶ月(9,900円)を反映済みです。

**Comment by kiyohara** [comment]
@cottondesu チェックしました。了解ですー

んでは、いったん清原の方で預かろうかと思います。
アマギフで 9,292 円分送っていただけますか :bow:
マスターの numbers の更新もしばらくは私がしておくようにしますね。
（といっても基本的には変動ないとは思いますが）

オフラインイベントをやるときにはまた相談させていただきたく！！

**Comment by cottondesu** [comment]
@kiyohara 
アマギフで9,292円送りました。確認お願いします。

はい、オフラインイベントが再開できたときにお金の管理の仕方を
含めてお話ししましょう。

**Comment by kiyohara** [comment]
@cottondesu 確認できました！
このissueとしては一旦クローズしますね。
対応ありがとうございます！
