### ISSUE TITLE
祝 10 周年ノベルティ

### ISSUE THREAD

**Issue by RyuseiNomi** [kanazawarb/meetup#1277]
## 概要

10 周年のノベルティについて、アイデア募集しております。

## 予算
合計 1 万円くらいを想定している

## ノベルティ候補

まだ未定です。
こちらの issue に URL などを貼っていただければと思います(･∀･)！！！

### 過去に作ったノベルティ
シール・キーホルダー・コースター・チロルチョコ・缶バッヂ・てぬぐい・栓抜き・カラビナキーホルダー、壁紙(online用)、Tシャツ、タンブラー

### 過去の issue
9周年：https://github.com/kanazawarb/meetup/issues/1221
7周年：https://github.com/kanazawarb/meetup/issues/1025
6周年 : https://github.com/kanazawarb/meetup/issues/879
5周年 : https://github.com/kanazawarb/meetup/issues/733
4周年 : https://github.com/kanazawarb/meetup/issues/612

## 配布方法

配布は 8/27 のmeetup での配布を検討しているが、間に合わない可能性もある。
現在は隔月でオフライン開催もやっているので、その度に配布をすることも考える。

**Comment by izawa** [comment]
@RyuseiNomi さん、issue立てありがとうございます！動けて無くて申し訳ないです……🙇‍♂️

というわけで、1万円ぐらいのノベルティ案募集中です。
なんにせよせっかく10周年なので「10th anniversary」 とか入れたいですね。

**Comment by muryoimpl** [comment]
ステッカーどうでしょう？
この一年はオフライン/オンライン両方開催がありえるので、オフラインはステッカー、オンラインはそのデータを元にした画像(バッジ) 的なものがあれば、オフラインで参加する人は記念としてステッカーもらえるし、オンラインで参加する人もブログ等では記念画像を貼ることができる。

画像があれば、仮に年末の LT をオンラインでやるとなったときにみんなに貼ってもらうこともできるかなぁとか思ったのでした。

**Comment by izawa** [comment]
ステッカー、こういうショップを見つけました。

https://otaclub.jp/products/category/sticker_print/diecut_sticker/?katamenryoumenmen=1147&cut_size=2840&seal_shurui=2900&checkbox1=1452&checkbox2=1453&mode=table

高耐候ダイカットステッカー

6cm四方、ホログラムレインボー クリアPP、ダイカット

50枚で税込み3,650円

8/1納品予定で、入稿締め切りが7/25

こんなかんじでどうかなぁ。
ホログラムレインボーは、高めの素材の例として計算するのに指定してます。
ダイカットだったらホログラムも何もないけど。

素材画像は別途必要ですが。

**Comment by RyuseiNomi** [comment]
サンプルのキャラクターが可愛い件

ステッカーは PC に貼ったりできるので用途としてもバッチリで良いかなと思います！🙌

**Comment by satoru-takeuchi** [comment]
ステッカーに賛成。自転車に貼りたいです

**Comment by PharaohKJ** [comment]
過去ステッカーの発注情報はココ

https://github.com/kanazawarb/meetup/issues/70#issuecomment-19868927

**Comment by kiyohara** [comment]
わたしもステッカー賛成です！ 👍 
素材画像、ただのロゴなら eps があるんですが…
10周年！って入れようとするとちょっと考えないとですね。ううむ 🤔

**Comment by kiyohara** [comment]
本件、担当してもらっている @izawa さんと少し話をしました。
準備の時期も迫っているので、 +1 たくさんもらえているステッカーで決定したいと思います！

■10th anniversary デザインどうする？
8th のときに壁紙作成でお世話になった、いちがみ兄貴に相談したところご快諾いただけました！
7月中旬から下旬を目安にデザイニングしていただけるよう、ご連絡とりあっていきたいと思います！

■発注先どうする？
期限的な話と、井澤さんのやりとりのしやすさを踏まえて、前述の [同人誌印刷所おたクラブ](https://otaclub.jp/) で進めさせてもらえればと！
7月25日までに入稿すれば8月の頭にモノをゲットできそうなので、このスケジュール感を目標に対応できればと。

※加藤さんが紹介してくれてる [株式会社ヤンバ](http://yanba.co.jp/wp/) の [:sparkles:激安短納期のシール印刷・ステッカー印刷・ラベル印刷は「シール印刷プロ」](https://seal.insatsu-tatsujin.net/wp/) も良い感じで甲乙つけがたい感じなのですが、発注対応してくれる井澤さんがやりやすそうな方選んでいただきました！
@PharaohKJ 紹介ありがとう！

**Comment by izawa** [comment]
ichigamiさんにカッチョイイ!デザインを作成していただいたので、こちらを使って発注していく予定

https://otaclub.jp/products/category/sticker_print/diecut_sticker/?katamenryoumenmen=1147&cut_size=2840&seal_shurui=2855&check3=hide&checkbox1=1452&checkbox2=1453&mode=table

高耐候ダイカットステッカー
サイズ: 6cm
用紙の種類と表面加工: 中粘着+クリアPP
カットの形状: キャラクターのアウトラインに沿った型抜きを希望
カットラインの不備時: カット指定で不備がある場合は弊社で修正して欲しい

発注数については、50個 3,650円でいこうと思っています。

**Comment by izawa** [comment]
入稿しました。
金額的には、送料300円で合計3,950円になりました。
商品が届いたら領収書の発行もしておこうと思います。

**Comment by izawa** [comment]
印刷業者より、「入稿データのチェックが完了しました」との連絡がありました。
これでデータ修正などの対応は無くてOKとの認識です。
2022/08/02発送予定とのこと。

**Comment by kiyohara** [comment]
@izawa cc @cottondesu 

ご対応ありがとうございます！！
こちらのお支払いですが、私から井澤さんになんらかの形（アマギフとか？）でお支払いしつつ、私は kzrb のお財布から同額を取り出すって流れでいけると良いかなと思うのですが、そんな流れで大丈夫ですか？

**Comment by izawa** [comment]
お気遣いありがとうございます。アマギフ通貨で大丈夫ですー！

**Comment by izawa** [comment]
領収書を取得しましたので共有します。
[receipt_mypage_20220803_22072500156-1.pdf](https://github.com/kanazawarb/meetup/files/9247469/receipt_mypage_20220803_22072500156-1.pdf)

**Comment by kiyohara** [comment]
@izawa ご対応ありがとうございます！
費用をアマギフでお送りしました！ご確認くださいー :bow:

**Comment by kiyohara** [comment]
@cottondesu 上記費用分を共有のお財布から引き落とさせていただきました！チェックくださいー 👍

**Comment by izawa** [comment]
アマギフ確認しました。ありがとうございます。

**Comment by kiyohara** [comment]
こちらはクローズして大丈夫そうですね。
何かあれば re-open ください :pray:
