### ISSUE TITLE
[2022/11/15 まで] Netlify で使っている build image を更新する必要がある

### ISSUE THREAD

**Issue by muryoimpl** [kanazawarb/meetup#1298]
Netlify で使っている image の更新が必要なようです。
11/15 までに対応しないと失敗するようになる、と言われている…

```
10:04:28 PM: ---------------------------------------------------------------------
DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022.

The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.
All Netlify builds using the Xenial build image will begin failing in the week of November 15th, 2022.

To avoid service disruption, please select a newer build image at the following link:
https://app.netlify.com/sites/meetup-kzrb-org/settings/deploys#build-image-selection

For more details, visit the build image migration guide:
https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239
```

**Comment by kiyohara** [comment]
@muryoimpl いったん、（meetupではなく） kanazawarb.github.com repo のデプロイについて調査しました。
 [こちらのドキュメント](https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239) をベースに、現行の最新で lock をかけつつ、イメージを Ubuntu Xenial 16.04 から Ubuntu Focal 20.04 に切り替えて手動デプロイを [試してみました](https://app.netlify.com/sites/kzrb-org/deploys/631d3c9ab9acb83dfe5ae437) 。

問題なくいけてるように見えるですが一方で、ruby のバージョンに対する warn がでてます。

```
10:40:42 AM: ---------------------------------------------------------------------
WARNING: Your site had a deprecated version of Ruby pinned (2.3.6), which is incompatible with this
build image. This build image only supports 2.4.x and later. We changed it to 2.7.2.

To learn how to set a custom Ruby version, visit the following link:
https://docs.netlify.com/configure-builds/manage-dependencies/#ruby

If you set a custom Ruby version lower than 2.4.x, you will need to select a different build image (Ubuntu Xenial 16.04).
The current build image only supports 2.4.x and later. You can select a different build image at the following link:
https://app.netlify.com/sites/kzrb-org/settings/deploys#build-image-selection
---------------------------------------------------------------------
```

> Your site had a deprecated version of Ruby pinned (2.3.6)

ってことなんですが、 `.ruby-version` は入れてないし、環境変数も特に設定してないんで、どこで？って気持ちですね。
この repo 的にはただのファイルコピーになっているはずなので、とりま lock は外しておきます。

meetup repo については、またタイミングをみてチェックしてみてますね。

**Comment by kiyohara** [comment]
作業まではできないのですが meetup repo の方、どんな感じかなーと思って眺めてましたが…

.ruby-version も Gemfile.lock も .gitignore な感じなんですね。
この辺、入れない方がより多くの人が扱いやすいって話なのかなぁ…
や、デプロイ環境のことを思ったら、これらも縛っていった方がいいのかなと。どうなんでしょうね。

**Comment by muryoimpl** [comment]
@kiyohara RubyKaigi で 2.7 はそろそろ○すって話しが出ていたので、3系にあげたほうがいいですね。
.ruby-version と Dockerfile もRuby のバージョンもってますが、バージョン上げるときに気にするファイルが多くなってしまうのでできれば少なめがいいなーというお気持ち。

固定しないほうが最新に追随しやすい（勝手になる）という初期の思想があったらしいのと、大きなバグに遭遇していない幸運が重なってですよね。縛っても更新していけば 🆗

**Comment by muryoimpl** [comment]
@kiyohara 
https://github.com/netlify/build-image/blob/focal/included_software.md を見ると、focal の default が 2.7.2、rvm で2.4以上が指定できる感じなので、focal デフォの[EOLが近い2.7系](https://endoflife.date/ruby) より .ruby-version 導入して rvm で 3系を導入するほうが手間が少なそう。ビルド関連でいくと、もしかしたら .rvmrc でのオプション指定も必要になるかも...というのはあります。

> .ruby-version も Gemfile.lock も .gitignore な感じなんですね。
> この辺、入れない方がより多くの人が扱いやすいって話なのかなぁ…

これは運用する/している人が容易にできる方法でいいと思います。環境も当時と異なるし、ボランティアベースだと運用続く or die になるので、やりやすい方法でもなんでもまず生き延びるのが一番と思っています。

**Comment by kiyohara** [comment]
memo:

meetup repo のデプロイも対応しました。ただこちらでも、前述の Ruby version に対する warn が出ている感じ。

> よく覚えてないですが、多分最初にデプロイした時のバージョンがNetlify側のDBで保存されていてそれを.ruby-versionとかの明確な変更がない限り使い続けるような仕様になっていると思います（なるべく意図しないビルドの失敗を防ぐため）。
> warningを見る限り「とりあえず2.7.2にしといたよ！」って感じだと思うので、特に特定のRuby versionに依存してなければこのまま放置でいいと思います。

といったフィードバックももらっているので、継続して出るかどうかに応じて対応策を検討するのがよいと思っています。

**Comment by kiyohara** [comment]
warn がとまるようであれば放置。
出続けるようであれば `RUBY_VERSION` env で縛るのがよさそう。

> Netlifyの自分のサイトは環境変数RUBY_VERSIONにバージョンを入れていて警告は出ていません。

**Comment by muryoimpl** [comment]
Ruby2系 EOL と、Netlify が 3系に対応したという話題が Slack で出ている
https://kzrb.slack.com/archives/C02A6KL82/p1674285563885599

**Comment by nagutabby** [comment]
対応済み
