### ISSUE TITLE
Meetup 詳細のページにある Doorkeeper の widget  が動作していない

### ISSUE THREAD

**Issue by muryoimpl** [kanazawarb/meetup#1343]
Doorkeeper の widget  が動作していない模様。
Slackでの指摘: https://kzrb.slack.com/archives/C02A6KL82/p1676122441110089

開催前のものは登録のリンクをクリックしても 204 が返ってくるだけ、開催後のものは ヘッダの kanazawa.rb へのリンクとメンバー加入リンクは生きているぽい。

| 開催前 | 開催後 |
| -- | -- |
| ![2023-02-12_000025_scrot](https://user-images.githubusercontent.com/318352/218265603-d53db694-1eeb-4be9-b85e-87c8f73c0856.png) | ![2023-02-11_235844_scrot](https://user-images.githubusercontent.com/318352/218265534-2b2cb023-d682-48dd-a1dc-830a294f87a9.png) |

Widget の情報が載っているページも長らく更新されていないぽいので、ただのリンクに変えるときが来たかもしれない。

Doorkeeper.jp の Developer resource:
https://www.doorkeeper.jp/developer/embeddable-javascript-widget?locale=en

**Comment by nagutabby** [comment]
```bash
% curl -i -X POST https://kzrb.doorkeeper.jp/events/151475/register/github
HTTP/1.1 204 No Content
Server: Cowboy
Date: Sat, 11 Feb 2023 15:30:16 GMT
Content-Length: 0
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Cache-Control: no-cache
X-Request-Id: 5414651c-adf9-4a46-baf3-a162cf3c5f57
X-Runtime: 0.013527
Strict-Transport-Security: max-age=63072000; includeSubDomains
Vary: Origin
Via: 1.1 vegur
```

以下のJSファイルがDoorkeeperのフォームを生成するようです

```
https://widgets.doorkeeper.jp/w/widget.js
```

生成されるHTMLファイルの例:

```
https://kzrb.doorkeeper.jp/events/151475/widget.html
```

**Comment by nagutabby** [comment]
かなり前に、新しいフォームに置き換えられたのではないでしょうか？
Doorkeeperにある現在のフォームとかなりデザインが違いますし、ソーシャルログインのPOST先のURLも違うようです

meetupサイトに埋め込まれているフォームのPOST先のURL:
```
https://kzrb.doorkeeper.jp/events/151475/register/[service name]
```
doorkeeper.jpで現在使われているフォームのPOST先のURL:
```
manage.doorkeeper.jp/user/auth/[service name]?origin=https%3A%2F%2Fkzrb.doorkeeper.jp%2Fevents%2F151475
```

**Comment by muryoimpl** [comment]
Doorkeeper に「この JS 今も動作サポートしてる？」って問い合わせている。
実際に確認できる環境 https://meetup.kzrb.org/126/ を案内して確認依頼しつつ、やりとり続けてます。

**Comment by muryoimpl** [comment]
お返事がこないな……次のイベントつくって Doorkeeper の widget が動かないなら、テンプレートの該当部分をイベントへのリンクに置き換える、というのをやってもよさそう。過去分はそのままでも怪我しないでしょう。

**Comment by kiyohara** [comment]
一応メモです。127 については、いったん手を入れずに前のものをそのまま使って公開しました :bow:

**Comment by muryoimpl** [comment]
了解です！(ちなみに、まだ連絡がありません…)

**Comment by kiyohara** [comment]
@muryoimpl 130 を作った際に気がついたことを共有まで。

https://github.com/kanazawarb/meetup/pull/1350 こちらのおかげで 130 のページに widget ではなくリンクが挿入されました。 💯 ですね！！

一方で、以前にリンクを挿入した 128 で、そのままリンクが残る形になっている点は改善の余地がありそうと思いました。
widget 時代はそのまま放置しておいても「申し込みの受付は終了したよ」と切り替わってくれたのですが、静的なリンクだとそういうわけにもいかないので、レポート作成時になんらかの文言に置き換えるとさらに便利になるかも！

**Comment by muryoimpl** [comment]
なるほど。リンクの文言がよろしくない感じ。
今回のmeetupが終わってるぞという判定ができれば、文言出し分けすればよさそう。パッと思いつくのは `next` を使うだけど、終わらないうちに次のページができる可能性はなきにしもあらずなので、ちょっと確認 & 考えます

**Comment by muryoimpl** [comment]
こちらはwidget使わずリンクに置き換える対応したのでクローズします。
問い合わせに対する回答はないので、きっとサポート対象外でしょうね。今後はないものとして扱いましょう！

**Comment by kiyohara** [comment]
> 問い合わせに対する回答はないので、きっとサポート対象外

つらい… でもまあ、経営的にあまり余裕ないようなので、致し方なし…

対応ありがとうございました！！ :pray:
