### ISSUE TITLE
meetup 129 イベント前対応 (cloudflare 会)

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#1351]
## イベント概要の決定
- [x] 日程を決定する
- [x] 内容を決定する
- [x] 場所を決定する

> slack 不要
- [x] ifttt の連携は切る

## 施設を予約する
- [x] 施設を決定する
- [x] 施設を予約する
- [x] （必要に応じて）利用費を事前に支払う

> 申し込みページはクラウドフレア側で用意する
- [x] meetup ページ PR を作成
- [x] meetup ページを公開
    - PRをマージ

## 告知活動を行う
- イベント概要決定時
    - [x] イベント日をカレンダーに登録する
- イベント公開時
    - [x] Doorkeeper(告知メール)
    - [x] Twitter
    - [x] Facebook
    - [x] ruby-jp slack
- イベント一週間前
    - [x] Doorkeeper(告知メール)
    - [x] Twitter
    - [x] Facebook
- イベント前々日
    - [x] Twitter
    - [x] Facebook

## 懇親会のお店を手配する
- [x] お店の選定
- [x] 予約の実施
- [ ] 人数の確定

**Comment by kiyohara** [comment]
2023/03/18 meetup 127 での議論

```
* 日時: 2023/05/20(Sat)
* 内容:
  + cloudflare 会
* 場所:
  + オフラインで開催したい
    - 研修室1はあいている

* 加藤さんのご紹介で cloudflare の勉強会をやろうという事になった
* 先方としては
  + meetup 会(cloudflare UG)を開きたいということだったがマッチしなさそう
  + 先方の用意する connpass を使いたいということだった
    - あくまで先方のイベントということになりそうだが
    - 前例は多数あるので問題なさそうとは思う

* 勉強会のレベルもいくつか選べそう
  + ハンズオンの形式もとれるとのこと
  + ざっとした説明＆ハンズオン会となると、参加者としては嬉しそう

* 日程については、先方とも合意出来ている

* いくつかのコミュニティと合同にするかどうか
  + 合同にやる場合、会場費用をどうするかが大きな検討事項
  + 逆にいえば、それ以外はそこまで大きな課題ではなさそう

* [結論]
  + オフラインの形式でやる
    - ITBP武蔵 研修室1
    - 費用は現地に集まる人から少しずつ集める形で
  + 申し込みは先方の connpass でよしとする
  + いくつかの勉強会合同で開催とする
    - Kanazawa.rb
    - Toyama.rb
    - ふくもく会(要調整)

* [ToDo]
  1. 会場費用について cloudflare になんらか調整の余地があるか確認する(加藤)
  2. ITBP武蔵 の予約を行う(大畑) ... 1 の結果次第で
  3. ふくもく会に声をかける(加藤)
    - 25日のイベントに加藤さんが直接突撃して話をする
  4. meetup repo に issue を作って情報をまとめる(加藤)
```

**Comment by PharaohKJ** [comment]
3/23(木) 19時 Cloudflareさまミーティング予定
3/25 ふくもく会参加予定

**Comment by PharaohKJ** [comment]
会場費→2万円まで補助だせるとのこと、領収書は加藤の名前でとっておく。
→いったん加藤が予約しました。 5/20・研修室1

枠組み→Cloudflare ユーザー会のconnpassで作りたい、イベント名にKanazawa.rbコラボと出すのはOK

![スクリーンショット 2023-03-23 19 46 15](https://user-images.githubusercontent.com/1581985/227181253-ef5c3e29-8f0c-48ed-808f-58024de90071.png)

**Comment by PharaohKJ** [comment]
Cloudflare の connpass でウェブサイトを公開しました。ご登録よろしくお願いします。

https://cfm-cts.connpass.com/event/281768

**Comment by kiyohara** [comment]
memo: 懇親会のお店は @PharaohKJ さんが手配済み

**Comment by kiyohara** [comment]
PR 作成済み https://github.com/kanazawarb/meetup/pull/1359
@PharaohKJ さんのレビュー待ち

**Comment by kiyohara** [comment]
twitter の `#kzrb` タグを slack に流し込む ifttt は無効化済み。
今回、流し込む先となる meetup129 チャネルがないため。

**Comment by kiyohara** [comment]
カレンダー登録 done.

**Comment by kiyohara** [comment]
tw, fb のアナウンス文案（レビュー済み）

```
「Cloudflare Meetup Kanazawa Kick off!!」を2023年5月20日(土)に開催します。インターネット全体の高機能化や高速化を司る Cloudflare の公式 meetup を Kanazawa.rb をはじめとする勉強会コミュニティがバックアップ。場所は「ITビジネスプラザ武蔵」。

#kzrb

https://cfm-cts.connpass.com/event/281768/
```

ドアキメール文案（イベントページ内容と同等なのでレビュー不要との認識）

Subject: `2023-05-20 - Cloudflare Meetup Kanazawa Kick off!! (kanazawa.rb meetup #129) `
Body:
```
# Cloudflare Meetup Kanazawa Kick off!! (meetup #129)

Kanazawa.rb, [Toyama.rb](https://toyamarb.github.io/), [ふくもく会](https://fukumoku.connpass.com/) の三つの勉強会コミュニティのバックアップのもと、 [Cloudflare](https://www.cloudflare.com/ja-jp/) の公式 meetup が金沢で開催されます。

* 日時: 2023年05月20日(土) 14:30 - 17:00
* 会場: ITビジネスプラザ武蔵 第一会議室 金沢市武蔵町14番31号 [http://www.bp-musashi.jp/](http://www.bp-musashi.jp/)
* 参加費: 無料

インターネット全体の高機能化や高速化を司る Cloudflare. 
代表的なサービスである CDN だけにとどまらず、多様なサービスが次々と追加されています。
2023年の今、どういったサービスがあり、どういった用途に使えるのか、基本的なところから網羅的にお話を伺い、自分たちのサービス運用に活用しましょう！

みなさんぜひご参加ください。

参加をご希望の方は以下のページからお申し込みください。

[Cloudflare Meetup Kanazawa Kick off\!\! \- connpass](https://cfm-cts.connpass.com/event/281768/)

```

**Comment by kiyohara** [comment]
ドアキのメールは配信済み。一週間前の予約送信設定も済み。
tw, fb は buffer に設定済み。
ruby-jp slack には手動で書き込み済み。

**Comment by kiyohara** [comment]
イベント終了につきクローズ
