### ISSUE TITLE
祝 11 周年ノベルティ

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#1364]
11 周年のノベルティに関する調整。
予算もスケジュールもあまりないので、どういった対応とするか検討させていただければと。

11周年会は、おそらく8月19日(土) に実施されるであろう meetup 132 となる見通し。
日程と同様に、オンラインになるかオフラインになるかもまだ未確定との認識。

ref. 
10周年 : https://github.com/kanazawarb/meetup/issues/1277
9周年：https://github.com/kanazawarb/meetup/issues/1221
7周年：https://github.com/kanazawarb/meetup/issues/1025
6周年 : https://github.com/kanazawarb/meetup/issues/879
5周年 : https://github.com/kanazawarb/meetup/issues/733
4周年 : https://github.com/kanazawarb/meetup/issues/612

**Comment by satoru-takeuchi** [comment]
- ステッカー
- 付箋
https://novelty.raksul.com/categories/sticky-notes/sticky-note?utm_source=google&utm_medium=cpc&utm_campaign=gsem_sticky-note_novelty&utm_term=%E4%BB%98%E7%AE%8B%20%E5%90%8D%E5%85%A5%E3%82%8C&gclid=CjwKCAjws7WkBhBFEiwAIi1687A9Rq2XWP2meZbRpxP1sw-uVIGarQ0nANpoDSpE0D8T9bonEpf0XRoCx3oQAvD_BwE/

**Comment by trans-r-miura** [comment]
昨年、今年、色々ありまして、厄除けのお守りがあればなと思いました。私の好みです。

- https://kobe-nagasawa.co.jp/originalgoods/cat/generalgoods/amulet/
- https://zeroone01.jp/omamori.html

**Comment by izawa** [comment]
付箋いいなーと思いました。
100冊からスタートってところがなかなか大量になっちゃいそうですが、それで進めてみようかとおもいます。

**Comment by izawa** [comment]
![スクリーンショット 2023-07-04 13 52 52](https://github.com/kanazawarb/meetup/assets/340622/5ca7dbed-3948-4f36-9c72-75d960892b8d)
こんなかんじでどうでしょうね。

**Comment by izawa** [comment]
@trans-r-miura せんせい、厄除けのお守りは神社に行って貰いましょう☺️

**Comment by izawa** [comment]
![スクリーンショット 2023-07-04 14 06 37](https://github.com/kanazawarb/meetup/assets/340622/42d45969-ae85-412b-954d-f16a6c762f24)
なにか11周年記念的な文字を入れたほうがいいね。

**Comment by izawa** [comment]
![スクリーンショット 2023-07-04 14 11 06](https://github.com/kanazawarb/meetup/assets/340622/3024bcef-dba9-4b67-925f-b693f4cfe44b)

何度もすみません、これでfixしようかと思いますが、コメントあればお願いします。
最短出荷日が07月26日(水)予定なので、近々発注しようと思います。
最小単位の20枚つづり100冊作成で、全国送料無料 ¥24,420

**Comment by kiyohara** [comment]
付箋は私もとてもよいと思います！こんないい感じのデザインいれられるんですね :)
是非付箋で進めていただければと思います。

費用についてどうするかは、要調整だと思っています。
ここは次の運営ブレストなどで検討させていただければと！

（議論をまってから発注していると、いろいろ間に合わないと思うので、先行的に進めていただいてよいと思っています。最悪、有志からのカンパで… 😅

**Comment by izawa** [comment]
こちら発注しました。

```
■ ご注文内容
────────────────────────────────

注文番号　　　　： N230705-3950670958
注文日時　　　　： 2023年07月05日(水)
お支払い方法　　： クレジットカード
お支払い金額　　： ¥24,420
お支払い金額内訳：
[N230705-3950670958-1] 【全ページ印刷】オリジナルカバー無し付箋 Cタイプ：¥22,200
────────────────────────────────
商品価格合計　　： ¥22,200
決済手数料　　　： ¥0
送料　　　　　　： ¥0
────────────────────────────────
小計　　　　　　： ¥22,200
消費税　　　　　： ¥2,220
────────────────────────────────
ご請求金額合計　： ¥24,420
```

**Comment by izawa** [comment]
> 出荷予定日　　　　： 2023年07月27日(木)
とのことなので、今月末には私の手元に届く予定です

**Comment by izawa** [comment]
![IMG_0666](https://github.com/kanazawarb/meetup/assets/340622/4fb1c5e5-c37a-4508-9a0a-927363cc9725)
届きました。薄い。数に余裕があれば、複数個持って行ってもらってもいいかも。

**Comment by izawa** [comment]
@kiyohara せっかくなので、8月の集客ツイートに画像使ってもらったら良いかもですね。

**Comment by kiyohara** [comment]
@muryoimpl @cottondesu @TAKAyukiatkwsk @satoru-takeuchi @nagutabby 
こちらのノベルティの費用について、現状 @izawa さんに ¥24,420 をかぶってもらってる状態になっています。
一方で、kzrb のお財布には現状 ¥20,540 しかありません。
次回の meetup 133 でこのあたり調整させてもらえればとー :pray:

**Comment by kiyohara** [comment]
井澤さんのお名前を Souvenirs ページに記載しつつ、寄付という形でいただく事とした。
クローズしますー。
