### ISSUE TITLE
meetup 132 イベント前対応

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#1365]
## イベント概要の決定
- [x] 日程を決定する
- [x] 内容を決定する
- [x] 場所を決定する

## Slack 準備
- [x] Slack に専用チャネルを作成する

## 施設を予約する
- [x] 施設を決定する
- [x] 施設を予約する
- [x] （必要に応じて）利用費を事前に支払う

## 申し込みページを作成する
- [x] Doorkeeper イベントを未公開状態で作成
    - meetup ページ URL は仮で
- [x] meetup ページ PR を作成
    - Doorkeeper イベントのウィジェットをいれこむ
- [x] meetup ページを公開
    - PRをマージ
- [x] Doorkeeper イベントを公開

## 告知活動を行う
- イベント概要決定時
    - [x] イベント日をカレンダーに登録する
- イベント公開時
    - [x] Doorkeeper(告知メール)
    - [x] Twitter
    - [x] Facebook
    - [x] ruby-jp slack
- イベント一週間前
    - [x] Doorkeeper(告知メール)
    - [x] Twitter
    - [x] Facebook
- イベント前々日
    - [x] Twitter
    - [x] Facebook

## 懇親会のお店を手配する
- [ ] お店の選定
- [ ] 予約の実施
- [ ] 人数の確定

**Comment by cottondesu** [comment]
施設予約の兼ね合いもあってmeetup131よりも先にmeetup132のissueを作成します。

以下meetup 128 運用ブレストログから抜粋

## meetup 132

* 日時: 2023/08/19(Sat)
* 内容:
  + 11周年記念会になる見通し
* 場所:
  + オンライン or オフライン


内容は例年通り「祝11周年 LT大会」
でオフライン開催を考えています。
今現6/18現在で8/19(土) ITビジネスプラザ武蔵 研修室1は空いています。

2名以上の賛成または6/21(水)までに反対意見がなければ
ITビジネスプラザ武蔵 研修室1を予約しようと思います。
検討よろしくお願いします。

**Comment by cottondesu** [comment]
研修室1を予約しようとしましたが、6/22 20:15時点で予約されていました。
情報化研修室は予約できそうですが、予約画面からプロジェクターの貸出台数を入力欄が
編集不可になっており、借りることができなさそうです。

8月26日(土)だと研修室2なら予約できそうなのですが、どうしますか？
意見ください。

**Comment by izawa** [comment]
研修室2に一票かな〜

**Comment by izawa** [comment]
meetup128以降、まともに運営ミーティングが出来ていない状況なので、ここで決めておいたほうが良いと思うのですが、
meetup132は、オフライン実施で良いですか？ >ALL

良ければ:+1:ボタン、オフラインのほうが良いと思う方は:-1: をこの投稿にリアクションつけていただきたく

**Comment by kiyohara** [comment]
いろいろと動きが後手にまわっており申し訳ないです :bow:

* meetup 132 をオフラインで実施すること → 賛成です
* 日時を（いつもの第三土曜である）8月19日から8月26日に変更して研修室2を予約すること → 賛成です

**Comment by cottondesu** [comment]
8月26日でITビジネスプラザ武蔵 研修室2を予約しました。
入金が終わったタイミングでまた追記します。

**Comment by izawa** [comment]
👍 を5件もらえたので、meetup132はオフラインで8/26開催でfixでお願いします

**Comment by cottondesu** [comment]
[8月26日ITビジネスプラザ武蔵 研修室2]の施設料の
支払いをしてきました。
領収証書はmeetup130のフォルダに格納済みです。
Kyashから4,370円出金済みです。
レポートページにも反映させるのでもう少し待ってください。

**Comment by kiyohara** [comment]
取り急ぎ、以下を対応しましたー

- Slack チャネル作成
- Zoom は今回使わないとの認識なので、上記タスクリストから削除
- ifttt はもう使えないので、上記タスクリストから削除
- イベントをカレンダーに登録

**Comment by kiyohara** [comment]
meetup page PR : https://github.com/kanazawarb/meetup/pull/1377
ドアキイベントページ（ドラフト） : https://manage.doorkeeper.jp/groups/kzrb/events/161435

**Comment by kiyohara** [comment]
PR は @cottondesu 先生のレビューを経てマージ済み。
ドアキ、イベント公開 done. メール告知 done.
ドアキの再告知メールも設定済み。
tw, fb は buffer に設定済み。
ruby-jp slack には書き込み済み。

懇親会は、特に何も準備せず現地で行きたい人が行く形になるとの認識です。

というわけでクローズできるかと！（なにかれば re-open ください :pray:
