### ISSUE TITLE
新しく環境構築すると NoMethodError: tainted? で落ちる

### ISSUE THREAD

**Issue by muryoimpl** [kanazawarb/meetup#1396]
Ruby 3.2.2 時点ではすでに tainted? がなくなっているので、liquid 5 にしないとNoMethodError で落ちちゃうっぽい。
```
/Users/muryoimpl/ghq/github.com/kanazawarb/meetup/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "en-US":String (NoMethodError)
```

https://github.com/Shopify/liquid/blob/main/History.md#500--2021-01-06 でtaint support が削除されているので 5.0.0 以上にしなければならないっぽい。just-the-docs のバージョンあげると解決するのか？要調査。

**Comment by muryoimpl** [comment]
liquid 4.0.4でとりあえず動くみたい。本家の just-the-docs の依存も4.0.4 になっているので、これで一旦進める。

Gemfile.lock がコミットされていないので、環境別で問題の発生有無がでているのでは？というところに戻ってくるね。

これ、もうGemfile.lock 入れていいんじゃないですかね？just-the-docs側もGemfile.lockを入れたことによってdependabot が動作するように環境が整えられているので、意図しないバージョンのおいてけぼりはなくなるんじゃない？というのと、環境が動かなくなることでkzrbメンバーが使いたくない…となるほうが問題ではないか？と思ってます。

**Comment by kiyohara** [comment]
@muryoimpl 同意です。 Gemfile.lock いれていきましょう。
以前から議論にあがりつつ、明確な「入れない理由」があったわけではないと認識してます。
どっちでもいいんだけど、ないほうが若干よい面あるよねみたいな。
けど、現状では実害の方が大きく出ているということだと思うので、縛っていきましょう、という気持ちですね。

**Comment by muryoimpl** [comment]
ありがとうございます！Slack ↓でも :ok: いただいているので、Gemfile.lock 含めるようにしますね。
https://kzrb.slack.com/archives/C02A6KL80/p1701144148735009

Gemfile.lock のPLATFORMS はもしかするとお手元の環境で差分でちゃうかもしれないけど、それは都度対応で。

**Comment by muryoimpl** [comment]
https://github.com/kanazawarb/meetup/pull/1399 の https://github.com/kanazawarb/meetup/pull/1399/commits/f1b71e19eca04eed6615b4f224b58544b0d0db42 でGemfile.lockを導入しました。
.gitignore の記述も削除しています。

**Comment by muryoimpl** [comment]
#1399 をマージしたので、Gemfile.lock 入りました！
