### ISSUE TITLE
Update copyright notice in the footer

### ISSUE THREAD

**Issue by nakanolab** [kanazawarb/meetup#1427]
_config.yml で定義されている

> Copyright &copy; 2012 Kanazawa.rb

ですが、放置されている感があるので、2024 もしくは 2012-2024 にしたら良いのではないかと思います。

**Comment by kiyohara** [comment]
なるほど確かに更新すると良さそうですね！ 😄 
対応してみますー

**Comment by kiyohara** [comment]
@nakanolab 対応してみました 😄 
良さそうならクローズくださいー 💪

**Comment by nakanolab** [comment]
確認しました。どうもありがとうございました！
