### ISSUE TITLE
三県合同 meetupの施設料支払

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#1473]
meetup148(2025/01/18)の施設料6,910円を支払してきました。
領収証書と納入通知書をmeetup146フォルダに格納済みです。

Kyashから6,910円を出金しました。
本issueはmeetup146のレポートページに三県合同meetupを
明記したタイミングでクローズにします。

**Comment by kiyohara** [comment]
@cottondesu 対応ありがとうございます！感謝！！
クローズタイミングの件も承知ですー :pray:
