### ISSUE TITLE
meetup29 レポートページを作成する(github pages)

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#410]

**Comment by cottondesu** [comment]
meetup29の収支は以下のようになりました。
meetup29 レポートページへの記載よろしくお願いします

<table>
<tr><td>項目</td><td>金額</td><td>補足          </td></tr>
<tr><td>部屋代 + 冷暖房費</td><td>0円</td><td></td></tr>
<tr><td>参加費合計(12名)</td><td>6,000円</td><td>3名社割</td></tr>
<tr><td>県外LT支援(2名)</td><td>-2,000円</td><td></td></tr>
<tr><td>二次会の余剰金</td><td>1,625円</td><td></td></tr>
<tr><td>meetup#28 くり越し</td><td>51,320円</td><td></td></tr>
<tr><td>合計</td><td>56,945円</td><td></td></tr>
</table>

**Comment by kiyohara** [comment]
@cottondesu 先生がいいがにしてくれたのでクローズ
