### ISSUE TITLE
meetup30 写真アルバムを作成する(30days)

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#424]

**Comment by izawa** [comment]
作成して手持ちの分はアップした。

http://30d.jp/kzrb/20

写真をおもちの方はアップロードよろしくです。

**Comment by kiyohara** [comment]
アップしておきました。
他にはいなさそうなので、夜にでもクローズですかね。

**Comment by kiyohara** [comment]
クローズします。

※清原のグロ画像を一枚消しておいた :p

**Comment by cottondesu** [comment]
tomo さんから写真アップロードしてもらいました！！

**Comment by kiyohara** [comment]
ありがたいですな！(・∀・)
