### ISSUE TITLE
meetup30 レポートページを作成する(github pages)

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#426]

**Comment by cottondesu** [comment]
meetup30の収支は以下のようになりました。
meetup30 レポートページへの記載よろしくお願いします

<table>
<tr><td>項目</td><td>金額</td><td>補足          </td></tr>
<tr><td>部屋代 + 冷暖房費</td><td>-4,300円</td><td></td></tr>
<tr><td>参加費合計(11名)</td><td>5,500円</td><td></td></tr>
<tr><td>学生支援(1名)</td><td>-1,000円</td><td></td></tr>
<tr><td>二次会の余剰金</td><td>364円</td><td></td></tr>
<tr><td>三次会の余剰金</td><td>250円</td><td></td></tr>
<tr><td>meetup#29 くり越し</td><td>56,945円</td><td></td></tr>
<tr><td>合計</td><td>57,759円</td><td></td></tr>
</table>

**Comment by izawa** [comment]
:+1:

**Comment by kiyohara** [comment]
ブレストログのリンクも追加完了したので、完成。
@cottondesu 先生、マージ thx
この後アナウンスする。
