### ISSUE TITLE
meetup34 JAWS-UG北陸-Hokuriku.netとのコラボイベント

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#449]
4月、5月とも、タイミングあわないので、6月でどうか？というステータスです。
問題なければ6月で進めたいと思いますのでご意見ください。
4月のmeetupで確定させて、以下、手配したいと思います。

- [x] 実行日の確定
  - [ ] ネタの要望
  - [x] JAWS-UG北陸/金沢と合意

**Comment by PharaohKJ** [comment]
6/20(第三土曜日) で打診中です。4月のmeetupで議題に出します。

**Comment by yuuitiro** [comment]
meetupに参加出来てなくてすみません。
調整に協力したいと思います。

**Comment by cottondesu** [comment]
hokuriku.net側も6/20でコラボ調整出来ないかお願いしています。

理想はmeetup31 運営ブレストログに書いてあるように
Kanazawa.rb x JAWS-UG x Hokuriku.NET 3つでの合同ですが、難しい場合は
どちらかとコラボできればいいなと思っています。

meetup31 運営ブレストログ
https://github.com/kanazawarb/meetup/wiki/meetup31-%E9%81%8B%E5%96%B6%E3%83%96%E3%83%AC%E3%82%B9%E3%83%88%E3%83%AD%E3%82%B0

**Comment by yuuitiro** [comment]
北陸でコミュニティのパイが大きくない中で、集客の面ではまとまることのメリットはありそうです。
コンテンツの内容次第ではありますが。

**Comment by cottondesu** [comment]
もし、3つ合同になった場合、開催場所の問題が発生します。
近江町交流プラザ、ITビジネスプラザ武蔵の大部屋は既に埋まっていました。
その他の候補としては、石川高専、勤労プラザ、金沢工大ですかね…。

**Comment by PharaohKJ** [comment]
ok

とりあえず、議論をfacebook上でやることにする、イベントを作成して
主要メンバーを呼び込んでやります。

すでに作成したので、進捗あったらここで報告などします。

**Comment by PharaohKJ** [comment]
日時 6/20
場所 石川高専

まで確定しました。あとは内容だな・・・。

**Comment by PharaohKJ** [comment]
テーマはクラウドについて、で、どうか？とfacebook上で調整中。進捗報告。

- 1時間 - Hokuriku.NET
- 1時間 - JAWS-UG金沢
- 1時間 - kanazawa.rb
- 1時間 - セッション

というような時間割りで

1時間各コミュでやってほしい
他コミュに質問があればセッションをしたいと思う、どうか？

という打診中。いまのところOKが帰ってきている。

- JAWS-UG北陸 → 議論中
- Hokuriku.NET → @kabakiyoさんに打診、イベント(de:code)でメンツと会うので
手配しますとのこと

kanazawa.rb内については、今週末、話しましょう。

**Comment by PharaohKJ** [comment]
各位に今週中には欲しいと連絡済み。

**Comment by PharaohKJ** [comment]
なうイベント中。もうやってる。終わっとく。
