### ISSUE TITLE
「githubを使ったissueベースの運用方法」をwikiをつかって展開する

### ISSUE THREAD

**Issue by izawa** [kanazawarb/meetup#45]
わたなべさん ( @wtnabe )のナレッジを展開するため。

**Comment by PharaohKJ** [comment]
もう閉じてよくね？これ。いいよね？ @wtnabe

**Comment by kiyohara** [comment]
運営にかかるドキュメンテーションは継続的に必要との認識ですが、本 Issue が意図していた内容とはすでに乖離が生じているので、本 Issue はクローズします。
もちろん、必要に応じて re-open もありです > @wtnabe
