### ISSUE TITLE
meetup 33の内容どうする

### ISSUE THREAD

**Issue by wtnabe** [kanazawarb/meetup#450]
5月には何かできるんじゃないかなーと以前、雑に振りましたが、JAWS方面が6月になる算段( see #449)なので、meetup 33の内容がぽっかり空いた状態となってます。

meetup 32から33までは時間が少ない（GW中に頑張るならともかく）ので、現時点である程度内容が見える状態を目指しておくことが必要かと思います。

### 特にない場合

 * さらに「もくもく会」を引っ張る

正直、ちょっとさすがにどうなんだろうという気がしてます。

### wtnabeのとりあえず案

 1. APIをテーマに何か発表を用意
   * APIってなんだべ
   * APIを使う
   * APIを作る（API開発をする際の工夫とか）
 2. 質問持ち寄り会

1 についてはwtnabeの方は gyunyu, ical2gcal, ga-shikomi の gem で API を利用するツールの開発についてちょっと喋ることができます。

API を提供する側の開発についても喋りたいところではありますが、今のところオープンにできるものがないっす。

2 は前もやったやつですね。「もくもく」ばかりだとさすがに手抜き感がアレなので、目先を変えつつ、準備がヘビーにならないものでワイワイとした感じに仕立てる。

まぁ、実質いつもの「もくもく」とあまり変わらない可能性はありますが、比重を「もくもく」から「わいわい」にしようかなと。飲まないうちに聞いておきたいこととかをどんどん喋っちゃおうぜという感じで。

**Comment by izawa** [comment]
いいんじゃないっすか。
APIっていう枠ってかなり広いので、いろんな話ができそうだし、適度にゆるいテーマ設定だと思います。

**Comment by wtnabe** [comment]
じゃあいっちょ目指してみましょうかー

**Comment by PharaohKJ** [comment]
私もネタあると思いますわ。それでいきましょう。

**Comment by kiyohara** [comment]
いちおうリマインドとして。
以下、ToDo

- [ ] イベント名の決定 ( @wtnabe )
- [ ] 登壇者の追加調整 ( みんな )

**Comment by wtnabe** [comment]
「Web APIでわいわいしちゃうぞ☆」

**Comment by kiyohara** [comment]
では、それで :+1:

**Comment by kiyohara** [comment]
さすがに二週間前には申し込み準備を整えたい気もするので、内容は一旦 fix にしますかね。
登壇者のトコロをどうするってのが残件だと思うけど、随時更新中とかなんとか書いておけばよいように思う。

**Comment by kiyohara** [comment]
残り時間も少ないので、方針だけはざっくり決めちゃいたい。
二つの課題があると思ってます。

1. イベントページをさっさと作りたいのだけど、どんな内容で書くべきか（≒イベント内容）が fix してない
2. 発表者を公募する仕組みが fix していない

---
以下は @kiyohara がイメージしている方針。

1. 話者も内容もギリギリまで決まらないことを鑑みるに「セミナー」という体は難しそう。
なので、「Web API をキーワードにした LT 大会」という体で進める。
話者は随時申し込みを受け付ける。受付方法については後述。

2. 話者を公募する仕組みは、 Issue を流用する方式でとりあえず対応する。
具体的には、「meetup 33 発表者宣言フォーム」ぐらいの内容で Issue をあげて、いろんなトコロの告知に「発表してくれる人はこの URL にコメントを書き込んでね」と書いておく形。
github アカウントが必須になるし、ベストの解法だとは思ってないけど、すぐに＆ローコストでできるのはこんなトコロかなと言う印象。

それでイイヨって人は :+1: をコメントくだされ。3 :+1: 集まったら Go します。
集まらなくても、明日(2015/05/02) の昼過ぎをリミットとしたいところ。
それ困るっていう人は、対案付きでコメントシクヨロ :wink:

**Comment by izawa** [comment]
:+1:

**Comment by cottondesu** [comment]
:+1:

**Comment by tokkie07** [comment]
:+1:

**Comment by PharaohKJ** [comment]
:+1: 

あと、登壇者については、 doorkeeperのメッセージ機能で送ってくれたら運営側で対応、
でよいのではないでしょうか。昔はそういう運用だったような？

**Comment by kkabetani** [comment]
:+1:

**Comment by kiyohara** [comment]
おーけー、んでは件の方針で進めませう。

> @PharaohKJ 
以前は確かにその手法でやろうとしてたね。
なんだけど、その方法だと、誰がどんな内容で手をあげているかがクローズドな情報になってしまって、他の参加者に見えないっていう問題があったんだよね。
ので、今回は github の issue でどうかなと思った次第。まあいろいろやってみて、改善につなげませう。
