### ISSUE TITLE
meetup 33 発表者向け宣言フォーム

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#460]
meetup 33 で発表してくれる方は、こちらのコメントで宣言してください。
以下の情報をご連絡ください。

* タイトル（必須）
* 概要（任意）
* 発表者名（任意: 未指定時は github アカウント名を使います）
* 時間（任意: 未指定時は 5min とします）

以下、 @wtnabe による例

 * Web APIとは？
 * まずはお手軽 webhook
 * API利用時に欠かせない秘密情報の話
 * 何はなくともJSONのお話
 * Web API設計について
 * API(サーバ|クライアント)開発時の便利ツール
 * API管理サービス

**Comment by kiyohara** [comment]
前回の運営ブレストで宣言していた

@wtnabe さん
@PharaohKJ さん
@izawa さん

内容を決め次第で結構ですので、是非とも書き込みヨロシクお願い致します :smile:

**Comment by wtnabe** [comment]
<dl>
  <dt>タイトル</dt>
  <dd>秘密情報と環境変数とdotenv</dd>
  <dt>概要</dt>
  <dd>Web API 利用時に欠かせない秘密情報（API key や secret key と呼ばれるもの）を環境変数経由で扱うケースが増えています。この環境変数経由で秘密情報を扱う実例とその際に便利に使える dotenv について紹介します。</dd>
  <dt>発表者</dt>
  <dd>@wtnabe</dd>
  <dt>時間</dt>
  <dd>15分(予定)</dd>
</dl>

**Comment by izawa** [comment]
<dl>
<dt>タイトル</dt>
<dd>最新プロトコル HTTP/2(SPDY) とは</dd>

<dt>概要</dt>
<dd>いまさらきけないHTTP/2とはなにか、HTTP/2の向き不向きなど。</dd>

<dt>発表者</dt>
<dd>@izawa</dd>

<dt>時間</dt>
<dd>10分</dd>
</dl>

**Comment by kiyohara** [comment]
* タイトル
  * Web API をデバッグするときに必要なたったひとつのこと

* 概要
  * ログって大事だよねって話

* 発表者
  * @kiyohara

* 時間
  * 10分

**Comment by PharaohKJ** [comment]
* タイトル
  * 俺とWeb API  - XML-RPCからREST -

* 概要
  * 俺と関わってきたWebAPIについて語る。呼ぶ側、呼ばれる側とその歴史。

* 発表者
  * @pharaohkj

* 時間
  * 15分

**Comment by kiyohara** [comment]
イベント終了したのでクローズ
