### ISSUE TITLE
meetup34 コラボイベント Hokuriku.NET部 内容調整

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#474]
- [ ] 1時間の内訳(担当・内容まで用意できたら)
- [ ] パネルディスカッション担当者名
- [ ] あれば他コミュへ質問

**Comment by kabakiyo** [comment]
## １時間の内訳
### 担当
日本マイクロソフト株式会社 エバンジェリスト 武田正樹 & 久森達郎

### タイトル
それでもボクはMicrosoft Azure を使う　~ OSS 開発者向け Azure 入門 ~
 
### 概要
OSS 開発者にとってMicrosoft Azure は本当に使えるのか？他のクラウドベンダーとの違いは何か？
そんな疑問にお答します。

## パネルディスカッション
### 担当
日本マイクロソフト株式会社 エバンジェリスト 武田正樹 & 久森達郎

**Comment by kabakiyo** [comment]
基本、MSさんに全部お任せっす！

**Comment by PharaohKJ** [comment]
ありがとうございます！！

**Comment by PharaohKJ** [comment]
@kabakiyo さん、エヴァンジェリストのおふたかたは、懇親会参加されますでしょうか？
すみませんが確認お手伝いいただけますか？

懇親会は

https://atnd.org/events/66304

です。

**Comment by PharaohKJ** [comment]
ATNDを編集しました。問題などありましたらツッコミお願いします。
https://atnd.org/events/66303

**Comment by PharaohKJ** [comment]
転記済み
