### ISSUE TITLE
meetup34 コラボイベント JAWS-UG北陸部 内容調整

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#475]
- [ ] 1時間の内訳(担当・内容まで用意できたら)
- [ ] パネルディスカッション担当者名
- [ ] あれば他コミュへ質問

**Comment by rch850** [comment]
福井方面から失礼します！
@kiyohara さんと話して、JAWS-UG 枠でひとつ頂くことになりました :raised_hands: 
内容や時間はおいおいということでお願いします。

**Comment by kiyohara** [comment]
:+1:

**Comment by PharaohKJ** [comment]
:+1: 
facebookに転記済み

**Comment by wtnabe** [comment]
:beer:

**Comment by PharaohKJ** [comment]
担当 :
@pharaohkj & @aibax

内容:
JAWS-UG北陸とは + AWSSummit 2015 いってきた！

時間:
40分

担当:
@rch850 

内容:
おいおい

時間: 
20分

**Comment by rch850** [comment]
@PharaohKJ 内容は「JAWS-UG福井支部とは + 落ちないサービスをAWSで」でお願いしますー

**Comment by PharaohKJ** [comment]
あざーっす！

**Comment by PharaohKJ** [comment]
転記済み
