### ISSUE TITLE
meetup34 コラボイベント Kanazawa.rb部 内容調整

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#476]
- [ ] 1時間の内訳(担当・内容まで用意できたら)
- [ ] パネルディスカッション担当者名
- [ ] あれば他コミュへ質問

**Comment by kiyohara** [comment]
前回の運営ブレストでは以下の様な方向とした。

- kanazawa.rb 枠で話す人
  - wtnabe (20min ぐらい)
  - kiyohara (20min ぐらい)
  - 要調整 (20min ぐらい)

- パネルで話す人
  - izawa

---

というわけで ToDo としては以下

- [ ] PaaS をつくった彼にオファー

**Comment by kiyohara** [comment]
PaaS の彼にオファーしたけど、その日は対応難しいという事でした。
というわけで、別の人に話を持ちかけるか、 @wtnabe , @kiyohara の枠を拡張するかの選択に迫られているでござる。
枠を大きくするのは正直シンドイので、だれかいい人いないかな… :sweat:

**Comment by wtnabe** [comment]
ぼくは @kiyohara 枠の拡大は十分可能というか、そもそも収まると思ってなかったので全然心配してないけど :grin: 発表の幅はあった方がいい気がしますねー。もっとぐっとライトなやつでも Kanazawa.rb っぽくていいと思うね。インターネットの向こうにリソースがありゃオッケーというくらいでいいし、「初めて○○やってみた」ぐらいのやつ。

**Comment by kiyohara** [comment]
「ライトな内容でいいから！」ってノリで、もう少し勧誘しましょう。
保険として、 kiyohara 枠は 20min でも 30min でも行けるように… い、いや、それは厳しいなぁ… :confused:

**Comment by wtnabe** [comment]
サマリ書いたよー

<dl>
  <dt>タイトル</dt>
  <dd>開発準備と運用を楽にするクラウドサービス始めました</dd>
  <dt>概要</dt>
  <dd>伝統的な開発においては開発の前にサーバ（環境）の構築をし、開発が終われば運用、監視に必要な仕組みをサーバに仕込み、deploy の手順を決め、遵守するといった開発以外のモロモロの準備が必要になることが当たり前でした。しかし昨今はこうした手間はできるだけ省き、「価値創出のための開発に集中し、そのスピードを上げていきたい」という要求が高まっています。今回はこうした手間を省いた開発、そしてモダンな運用ができるクラウドサービスを使ってみたので、そのご紹介をします。logging, SMTP, CI など。</dd>
  <dt>発表者</dt>
  <dd>@wtnabe</dd>
  <dt>時間</dt>
  <dd>15 〜 20分程度</dd>
</dl>

**Comment by PharaohKJ** [comment]
もしかして、 @kiyohara サン、 @wtnabe サン、以外のプレゼンターがいなくてヤバイ感じ？
なんとか今週中には内容つめて、明けにはウェブページで告知したいと考えています。

**Comment by kiyohara** [comment]
いい人を見つけられずにいる感じ。
自分はまだサマリーを書けていないのだけど、大体20分ぐらいになると思われ。
となると、kzrb 枠として20分あまる事になる。
誰かいい人、いないかな。

**Comment by wtnabe** [comment]
おれたぶん伸ばせるよ。（ログ、SMTP、CIに加えてパフォーマンス監視を追加できる。）まぁそれでもライトネタの方がいいなとは思ってるけど。ちょっとツバつける時間がなくてですね… :sob:

**Comment by PharaohKJ** [comment]
いったん、

@kiyohara 30分
@wtnabe 30分

としておきます。

**Comment by kiyohara** [comment]
@PharaohKJ 承知。がんばる。サマリーはもうちょっと… もうちょっとだけまって…

**Comment by kiyohara** [comment]
サマリ

* タイトル
  + Google Cloud Platform を支える技術、のごく一部

* 概要
  + Google Cloud Platform が利用しているいくつかのオープンソースソフトウェアをご紹介します。キーワードは Docker, Kubernetes(k8s) 等。

* 発表者
  + @kiyohara

* 時間
  + 30min

**Comment by PharaohKJ** [comment]
ありがとうございます。ATNDを更新しました。
