### ISSUE TITLE
meetup36 3年記念で何をしましょうか

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#479]
今までの実績として
・meetup#12(1年記念)ではステッカーを作成
・meetup#24(2年記念)ではノベルティーを作成

meetup#36(3年記念)では何をしましょうか？
meetup#35で少し詰めたいと思いますので、なんでも
いいので案、アイディアを下さい。

**Comment by kiyohara** [comment]
歌つくろうぜ、歌。CDにしよう。

**Comment by libero18** [comment]
時期が夏なので「うちわ」とか

以下のサイトだと「少部数(10本〜)に対応します」って
書いてあるので価格によっては良さそうかと

http://www.presstalk-direct.jp/category/uchiwa.html

**Comment by PharaohKJ** [comment]
3年間の知見を活かした運営アプリハッカソン​

**Comment by cottondesu** [comment]
meetup36記念品の案としては
・歌、CD？
・うちわ

meetup36の内容案としては
・3年間の知見を活かした運営アプリハッカソン

上記の案、内容については、meetup35で打ち合わせしましょう。

**Comment by izawa** [comment]
コルクのコースターとかどうだろうね。普段自分のデスクで使えそう。

**Comment by libero18** [comment]
+ 単価は高いと思うけど、瓶麦酒の栓としての形に拘ることできそう
   - [http://www.coasterkobo.com/item/item-kan03/item.html](http://www.coasterkobo.com/item/item-kan03/item.html)

+ 形状が普通の丸型で良ければもう少し安い
  - [http://www.coasterkobo.com/item/item-kan01/item.html](http://www.coasterkobo.com/item/item-kan01/item.html)

簡単に見てみた限りだと利用するサイトによってはラバーコースターでも
コルクコースターよりも高かったりするので探せばもっと安く作れるかも

紙のコースターは単価は安いけど、ロットが1000個とかなので、
予算とか色々なものがクリアできるなら通年で利用できるものが良いですね

**Comment by tokkie07** [comment]
無難にボールペンとかいいかなって思ってたんですが、コースターいいですね！
個人的にはコルクより、ラバーがいいと思います^_^
ラバーだったら、立体的な感じでカラーにできるし、かわいい感じになると思います！

**Comment by kiyohara** [comment]
コースターを作成することに決定。
以降は #492 で。
