### ISSUE TITLE
meetup36 3ノベルティーの作成

### ISSUE THREAD

**Issue by tokkie07** [kanazawarb/meetup#492]
meetup36で配るノベルティーの作成について。
作成するものはコースターに決定、
作成するパターンを２パターン考えています。

1.ラバーコースター
　丸または、角丸四角のラーバーコースターでkanazawarbのロゴをプリント
　http://www.fullmark18-31.com/product_04.html

2.コルクコースター
　コルクコースターの形をkanazawarbのロゴの形にして、ロゴをプリント
　http://www.coasterkobo.com/item/item-kan03/item.html

現在、2パターンとも費用をメールにて確認中
ホームページに書いてある感じだと、両方とも予算内になりそうです。

**Comment by cottondesu** [comment]
おお〜、素晴らしい。そして、行動が早い。

**Comment by tokkie07** [comment]
確認していた費用と納期の返答がありました。
両方とも50個作成した場合です。

1.ラバーコースター
　金額：￥36,180-
　納期：約２５日（営業日？）
2.コルクコースター
　金額：￥22,572-
　納期：５営業日

それと、ラバーとコルクどちらがいいか意見を伺いたいので、
下記のアドレスにイメージをアップしました。
http://30d.jp/not-too-late/2

注意点
1.ラバーの場合はロゴの周りに余白ができること。
　イメージは白が余白で、黒が背景です。
2.コルクコースターの場合は形がロゴの形になること、
　イメージでは白が背景です。

ラバーコースターで作成する場合、今月中には発注しないと危うそうなので、
来週末には皆さんの意見を参考にどちらで作成するか決めたいと思います。

**Comment by kiyohara** [comment]
コルクに +1

**Comment by wtnabe** [comment]
あの時出てた意見てなんだっけ？

 * コルクじゃなくてラバーの方が形成に自由度があるんじゃないか？
 * ラバーだとカラバリとかできそうだね

辺りだっけ？  あの場はラバー優勢だった気がしたけど。

自分は

 * ロゴの再現度にはあんまりこだわりはない
 * カラバリできるならやってみたい

なんだけど、カラバリの是非は別に問うた方がいいかしら？

**Comment by tokkie07** [comment]
カラバリの事も言っていただければいいです！

あの時（meetup35）に出てた意見としては、
　・コルクならロゴの形にできそう
　・ラバーなら色再現できるし、表面に凹凸も出来て、
　　置物としてもかわいいんじゃないか？
　・デザイン案は私（tokkie）にある程度お任せ

ってな感じだったかと、
ラバーが優勢だったのは主に自分が発言していたからだと思います。

一回の発注で複数の色違い（カラバリ）ができるかは確認してみます。

あと、ラバーの場合は
　・余白のスペースを何色にするか？
　　→カラバリが可能なら、ロゴの色に合った色を決めないといけいない
　・そもそも余白は色だけでいいのか（文字とかデザインは必要？）？
　　→日付や「meetup36」、「The 3rd Anniversary」とか入れちゃう？

といった事も考える必要があるのかなと思います。

**Comment by libero18** [comment]
コルクに +1

**Comment by cottondesu** [comment]
このロゴデザインとコルクがいい感じだと思うので、コルクに+1

**Comment by cottondesu** [comment]
@tokkie07 どちらに転んだとしても、いい値段の金額がするので事前に連絡頂ければ前払金としてお金をお渡ししますよ！！

**Comment by tokkie07** [comment]
@cottondesu 了解です、金額がわかったら連絡します！

ラバーコースターのカラバリについて報告。
遅くなってすみません、50個の注文の中で色を複数設定することはできないとのことでした。

作成するコースターに関して、意見の多かったコルクで作成したいと思います。

**Comment by tokkie07** [comment]
遅くなりすみません、コースターの注文完了の報告です。
金額は23,112円
内訳
　商品（送料込み）22,572円
　支払い時の振込手数料540円

ノベルティーをmeetup36で皆さんに配って、
料金を受け取ったら作業完了とみなし、このissueをcloseします。

**Comment by kiyohara** [comment]
@tokkie07 先生にはイイガニ支払われたものとの認識。
まだだったら reopen してね :)
