### ISSUE TITLE
meetup38 Rails勉強会の内容を詰める

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#513]
@wtnabe 先生、どうしましょう？

内容今度、どこかで詰めませんか？

----

こんなんでどうでしょう。(by @wtnabe)

タイトル
--------

「ぼくにもできた！Ralisハンズオン初級編！！」

コピー
------

Ruby on Rails って聞いたことはあるけどちょっと尻込みしてる。触ったことはあるんだけど、途中で挫折した or あんまりピンと来なかった。そんなあなたに朗報！ Kanazawa.rb は決して Rails に強いコミュニティではありませんが(笑)、Railsハンズオン、 **とりあえずやってみちゃう** から、ユー来ちゃいなYO !

対象
---

 * 動的なWebアプリの全体的な仕組みについて、ある程度の理解がある人
 * 何らかのサーバサイドプログラミングの経験が少しでもある人
 * RailsやRails-inspiredなモダンなフレームワークを使いこなし、考え方を理解したい人

会場に用意されているもの
-------------------------

 * WiFi
 * 電源

各自で用意してきてほしいもの
--------------------

 * **Railsのインストールされた** ノートPC
 * テーブルタップなど自分の電源を確保するためのもの

※ 今回 DMM さんのご好意により、午前の時間を使ってインストールのフォローを行います。インストールにてこずっている方は当日11:00にお越しください。

ゴール
-----

 * モダンWeb開発の考え方、ワークフローを理解する
 * scaffold + alpha で Model 2つ、association 1つの ToDo アプリを動かす

※ 今回は production 環境への deploy については扱いません。

タイムテーブル
------------

開始時刻               | 内容                                      |所要時間
--------------- |------------------------------------------ |-------
11:00 - 12:00   | 午前開場 and (インストールフォロー or もくもく )  | 1h
13:00           | 午後開場、受け付け                           | 15m
13:30 - 16:30   | ハンズオン＆トークセッション                  | 3h
16:30           | アフターフォローとか片付けとか                | 30m

**Comment by wtnabe** [comment]
@PharaohKJ あ、Rails勉強会なんてものがあるのね？ そうなのね？

**Comment by kiyohara** [comment]
https://github.com/kanazawarb/meetup/wiki/meetup36-%E9%81%8B%E5%96%B6%E3%83%96%E3%83%AC%E3%82%B9%E3%83%88%E3%83%AD%E3%82%B0

> * 以下のいずれか  
>   *「どっかで Docker どうでしょう」  
>   *「Ruby on Rails ハンズオン」

**Comment by wtnabe** [comment]
おぉ、なるほど

Railsというか最近フレームワークの Install Day みたいなのがあってもいいかなと思ってました。（RailsGirs は確か 1st day が install なのです。）午前中で install して午後から実際の内容に入る、みたいなのだとハンズオン的にボリュームが確保できて面白いかなと思うんですが、さすがに厳しいすかね。全然日程の都合とか考えずに書いてますが。

**Comment by wtnabe** [comment]
いったんの案として

 * 基本は install, rails new 済みの rails を持ってきてくれ
 * 不安な人は午前に一緒にやりましょう

という感じ。それができると午後の時間の計算がしやすいかなと思います。

**Comment by kiyohara** [comment]
そういえば Docker 会にするのか Rails 会にするのかの最終結論って出てたっけ？
いや Rails 会にするのは ruby コミュニティとして良い線だよねーと思っているのだけど、講師が集まらなかったらやりたくても出来ないという自体が…
@PharaohKJ 先生と @wtnabe 先生が講師やるよって流れでよいのかな？

**Comment by wtnabe** [comment]
@PharaohKJ  @kiyohara 実際にはハンズオンなんで講師だけいてもダメなんだけど、流れを組んでみていけそうならGO!でいいような気はしてます。今のところ入門者向けにRails GuideとかRails Tutorialとかから<s>つまみ食い</s>アレンジするのがいいんじゃないかと思ってますけど、そんな認識で合ってる？

**Comment by kiyohara** [comment]
なるほど、いいんじゃないですかね。

もうちょっと *確認* をしていこう。
ハンズオンの対象者レベルをどう設定するかによって結構やることが変わってくると思う。

1. rails って言葉は知ってるけど触ったことない人に、Hello world を教える
1. スカッフォルドを触った程度の人に、ロジックの組み方を教える
1. 一度アプリを作ったことがある人に、最新のテクニックを教える

どの辺の話が妥当かな。
今の話の流れだと (1) だよね。あってる？

**Comment by kiyohara** [comment]
あってる？って言い方は違うか。
自分は（そして @wtnabe さんも） (1) の認識だし、そのまま進めるけど誰も文句いわないよね？
ぐらいのキモチ。

**Comment by wtnabe** [comment]
個人的には 2 が見えてくるといいな、くらいですかね。ここを狙うのはもちろんnew comerのリクルートの意味もあります :smile: 

で、2 までいけるのが本当はいいよなということを考えた時に、「install は午前中に別フォロー」にするといいんじゃないかなと考えたのが上で出した話ですね。ネットワークの帯域的にもその場でみんなで install はつらいし、時間読みにくくなるから。

だから「railsをinstallしたPCを持ってきてください。installを手伝ってほしい人は午前中に来てね♡」がいいかなと思ってるのです。これに都合合わせられる人がまったくいないと厳しいから、そこも相談要るなーと思ってます。

一方で、もっと実践的な話がしたいという人もたぶんいて、そっちはそっちで別テーブルで勝手にわいわいやるのでいいかなという気はしてます。応用編のデモみたいなのも最後の方に合ってもいいかもしんない。

**Comment by wtnabe** [comment]
あ、午前中って勝手に書いたけど、場所によるのか。

**Comment by kiyohara** [comment]
午前中枠と午後枠を設けるのはすごく良い案だと思う。
@wtnabe さんが言ってくれてる通り、「場所」「要員」の問題をどうするか、だね。

場所としては、ネットワークが必須になる。
38 は DMM.com Labo さんを使わせてもらえることになっている。
午前中も使うことができるのか @bemarble さんに確認するところからではないかな。
「午前中も」となると、 @bemarble さん（もしくはいずれかの DMM.com Labo 社員さん）に午前中から付き合ってもらう事になるという、アレなアレはあるけど(^^;

要員については、 Install を教えられる人間ということになるね。
うーん、 @wtnabe さんは AM から動けそうなの？

**Comment by libero18** [comment]
ハンズオンやるなら、この前こっとん先生が言ってたように
[Rails Tutorial](http://tatsu-zine.com/books/railstutorial) を kanazawa.rb で購入して
参加者に頒布したうえで、その内容に沿ってやると良いかもねー

ライセンスが CC BY-SA 3.0 なので同ライセンスの条件に基づく限り、
自由に複製して頒布することができますし、

 (1) を想定するなら、最初の1回だけじゃなく終了後に継続的に学習を
出来る状態を作ることが望ましいと思うのと、他の参加者同士が
同じテキストを使って学習していけるようにすると準備に対する負荷も
軽減できるし、新しい参加者が増えるきっかけになるのではと思います

**Comment by wtnabe** [comment]
@kiyohara 今のところ10/17イケるつもりです。まだ確認は完全ではないけど。

**Comment by kiyohara** [comment]
To: @libero18 
内容を Rails Tutorial に沿ったものにするかどうかは、講師やってくれる人の意向次第だね。
動いてくれる人を最優先にすべきなので、 @wtnabe さん、 @PharaohKJ さんのやりやすい形で。

書籍を買って再配布するのはイマイチな気がする。
誰のアカウントに紐付かせるのとか、扱いの問題があるので。
Web 版を紹介するので十分じゃないかな？

http://railstutorial.jp/

To: @wtnabe 
@PharaohKJ さんにも確認して、「2名以上動ける」となったら AM 枠も作る方針とするのが良いのではないかな。つまり、AM枠の開催条件は以下。

- [ ] @bemarble さんが AM からの対応を快諾してくれること
- [ ] AM 枠講師が2名以上確保出来ること（ @wtnabe さんは内定 :p ）

ま、AM 枠を取れなかったとしても、（先に言ってもらえてるとおり）テーブルわけてやるので良いと思う。

- インストールやるぜテーブル
- もうちょっと進んだことやるぜテーブル

みたいな。どうでしょ。

**Comment by wtnabe** [comment]
テキストをどうするかはRailsでイケそうかどうか次第すね。購入の話は経緯をあんまりよく覚えてないので、別途考えてくれる人がいると助かります。

@kiyohara 最近気づいたけど、D社Railsやってるので、D社内で興味ある人抱き込めればBさんじゃなくても打診はできるかもしれないっすね。それ以外はほぼ同意です。

**Comment by kiyohara** [comment]
@wtnabe 
* 内容として「Rails チュートリアル」を使うか
  * 追々考えましょう。
  * 最終的な判断は @wtnabe さんにお願いしたく。

* （「Rails チュートリアル」を使うとした場合） ドキュメントの配付をするか
  * 選択肢としては以下
    1. Web 版を参考にしながらやる（配付はしない）
    1. Kanazawa.rb のお金で買って再配布する
    1. 清原が個人的に持ってる物を再配布する
  * 異論が無ければ (c) でよいですよ。

* DMM.com Labo さんに AM 対応してもらえるかについて
  * Rails 会であることを踏まえつつ、（ @bemarble さんに限らず） 誰かに対応してもらえないか確認する
  * 清原が声かけしますね。どこかで :p

こんな感じで。

**Comment by wtnabe** [comment]
ハンズオンのテキストについて試案を思いついたので投げます。もし続くようならIssue分けるなりしましょうか。

 **ネットワーク接続を必要としないしPCの画面を占有しない閲覧方法がある**

という意味で「紙」か「いずれかの電子書籍」にするっていうのは確かに有効な手だと思う。一方で、自分で勉強する気があるなら多少は身銭切った方がいいんじゃないの？という思いはあるし、逆に「一斉にやるならテキストは全員が持ってなくても十分ちゃ十分」。そのうえでニューカマーについて考えるなら、例えば

**懇親会のように学生支援という形でいくらかバック**

という手もあるような気はする。本人のものか確認が必要な気もしなくはないけど、そこは **申告をそのまま信じる** でもいいんじゃないかな。そんな何十人も相手にするわけでなし。

どんなもんでしょうか。

**Comment by cottondesu** [comment]
購入の話を言い出したのは私なのですが、もう一度言うと
Rails チュートリアルの内容に沿ってハンズオンをやるなら
Rails チュートリアルの実演動画を購入して参加者に配布したら
どうでしょうかって内容です。

あくまでも一案ですので、内容が決まったら
こちらも合わせて考えましょう。

**Comment by wtnabe** [comment]
@cottondesu ちなみに実演動画購入のURLはどこですか？

**Comment by cottondesu** [comment]
@wtnabe URLは記入してもらったものと一緒です。

はい、全部を買うとなるとなかなか良い値段です。
ここは重要って絞ってその章を買うっていうのもありかなと思います。
また蛇足としてコースターでそんなにお金が減りませんでした。

**Comment by PharaohKJ** [comment]
私の目的の1つとして
「Railsお勉強」
となのつくタイトルでやったらどこまで人が集まるかってのが一番の目的だったんだよなあ。
1) 2) か。

内容はまぁ、 @wtnabe 先生と私でnowなベストプラクティスを用意したほうがいいな、ぐらいに
しか思ってませんでした。
（Railsに手を出したいんだよな、って人の背中を押してやるぐらいな？
そしてもうできる人にはnowなお勉強のことを確認的な。)

私は、まずは午後にそのnowベストプラクティス Hello Worldができればよいとだけ思ったりしてます。

たとえば、そこで、そういう動画を紹介する。みたいな。


で、この場合、内容については、 `bundle install` できないとなかなか難しいとは思うので、
そこだけ注意が必要かなと思います。


とりあえず、 @wtnabe と @PharaohKJ のベストプラクティス発表 & Hello World ハンズオン
でどうでしょ？

その集客数、きてくれた人の反応を見てから、あの手この手を試すということで。

**Comment by kiyohara** [comment]
内容については @wtnabe さんと @PharaohKJ さんが何らかの合意に至ればそれで決定だと思っているのですが、まだその「合意」は得られていないとの認識。
なので、とりま @bemarble さんに AM という選択肢がありなのかどうか、問い合わせは実施致しました。
そもそもの選択肢としてテーブルにあげてよいかを明確にしておくのは、合意点に向かうため必要だと思ったので。
返事がもらえたらまた展開します。

**Comment by kiyohara** [comment]
@bemarble さんから、「AM からであっても対応可能」とのお返事を頂きました。
選択肢として検討くだされ。

**Comment by PharaohKJ** [comment]
:+1:

✉︎ from iPhone

**Comment by wtnabe** [comment]
@kiyohara あざます！

@PharaohKJ ちょっとマジメにタイムテーブル作ってみましょっか。インストールの時間を追い出すことはできそうだけど、それにしても

 * ハンズオンと発表を混ぜられるほど時間に余裕はない（なんだかんだで3時間ちょいくらいしかないはず）
 * ゴールをある程度明示しないと参加者は何を準備したらよいかも見えにくい
 * 何よりハンズオン参加者の持ち帰れる成果を最大化したい

と  wtnabe は思ってます。できれば特に初心者は休憩時間にわいわいできるといいかなー。（coderetreatのようなイメージ）

で、

 1. 初心者向けゴール
 2. 中級者向けゴール

を案内に出す、そのうえで参加者がどのレベルをやりたいかを答えてもらう、みたいな感じがいいかなぁ。（doorkeeperでコメント必須にできるんだっけ？）

ま、あくまでこれは理想でこっちの準備が間に合わない可能性もあるんだけど。とりあえず wtnabe はこの 2案作成にチャレンジしてみます。今度の週末までに間に合わなければ「1 案にまとめたうえで様子を見ながら」案でいきましょうか。あ、ということは 3案のタイムテーブルが要るのか。（どっちみち初心者向けはどうしても説明の比重が大きくなっちゃうんだろうけど）

----

今のところ

production deploy は行わない前提で、

 1. 初心者向けは
    * 外部プロセスなど標準で入る以外のgemを要求しない
 2. 中級者向けは
    * さすがにバージョン管理はやっときたい
    * よく使う依存gemを追加（bootstrapとかkaminariとか？）

ぐらいの大枠を思ってるけど、しかし、ちらっと読んだけどRailsチュートリアルはけっこう硬派だねぇ :sweat_smile:

**Comment by wtnabe** [comment]
Railsハンズオン初心者向けセッション案作った

方針

 1. モダンなWeb開発ワークフローに意識がいくように考えた
 2. Railsチュートリアルはなかったことにした
 3. TodoとNoteの2つのModelを持つアプリを動かすことを目指すことにした

https://gist.github.com/wtnabe/a6f92c235641c5fc8ff2

1 は欲張りすぎかもしれないけど、これ分かってないと Rails **触れるだけ** になっちゃうので、あんま意味ないかなーと思ってる。

どんなもんすかね？

**Comment by kiyohara** [comment]
@wtnabe @PharaohKJ meetup 38 の内容について、先週末の meetup 37 のなかで何らかの調整がなされたと思っているのだけど、ログ等は残ってますか？可能ならば運営ログとして起こしてもらいたいなと思ってます。

特にログはないということであれば、「決定・合意したこと」を列挙してもらえますか？
wiki 化は私の方でやりますので。

**Comment by wtnabe** [comment]
@kiyohara @PharaohKJ ログも何も「じゃあそれで」って言われただけなので…。逆に上に書いた部分についてコメントが欲しいです。結構前に書いてるんだよもん。

**Comment by PharaohKJ** [comment]
こんばんかきます。明日朝には

✉︎ from iPhone

**Comment by kiyohara** [comment]
@wtnabe 上記に書いてもらってる内容については全面的に同意（その内容で進めればよさそうと思った）です。 :+1: とか agree！！とか叫んでおいた方がよかったですね。申し訳なし。

個人的には @wtnabe さんと @PharaohKJ さんとの調整が大事だと思っていて、そこが「じゃあそれで」となったのであれば、書いてもらってる内容で fix なんだと思うデスよ。
とはいえ、「どんな話をして、どこを合意したのか」は明確にしておくとよいと思います。
その辺がクリアだと手伝えることも増えるでよ(・∀・)

**Comment by wtnabe** [comment]
@kiyohara @PharaohKJ :open_hands: うぇいうぇい！

えーとこの辺かな。

懸念点として挙がったものとしては

 * installはできてもdeployの段階で急に知らなきゃいけないことが増える
    * → deployは扱わない

で合意すかね。その後、懇親会で出たのが開発環境の話で、

 * dotinstallはVagrant前提になってるんだよね
 * Dockerでいんじゃねーの？
    * Dockerを入れるとこからか
 * クラウドでいんじゃねーの？（同日、たかざわっちが調べていて「いいと思いますよ」と言ってる）
    * @wtnabe の方でも Cloud 9 と Nitrous と Codenvy を試して、Cloud 9 よさげ

てな感じですかね。

**Comment by kiyohara** [comment]
@wtnabe なるほど、そういう話が追加されたんすね。把握でございますー。
一応どこかで、wiki 的なものにまとめておきますね。

**Comment by wtnabe** [comment]
@kiyohara あざます :meat_on_bone: おなかすいた

**Comment by PharaohKJ** [comment]
内容はこれでいきましょう。手分けの方法は、私がヘルプで @wtnabe さんが講師で。

今回は `rails s` までで、デプロイはまた今度。

はぁぁ〜見てたら思い出したんだけど、最初のハードル

- rbenv / rvm
- bundler

について、話あったほうがよかったかなぁ。
これはruby入門になるからまた別にしたほうがいいかな。

最初はおまじないってことにするか・・・。

まぁ、 事前準備済み(Linux + rbenv + SSH)、激安インスタンスを人数分並べてもいいよね。
お金かかったとしても会場費で賄えそうだ。

あっ、そのLinuxインスタンス準備しても、エディタvimだと初心者向けぽくないか。

**Comment by wtnabe** [comment]
rbenv と bundler については pre-session talk で賄うつもりです。以前社内用に作った資料があるので、それベースでスッといきます。ものすごく詳細に説明する必要はなくて、 **「すべてがプロジェクトで閉じている状態が大事」** という話です。これがdeployの自動化に繋がるので。（だからDockerとかの話は逆にしたくなかったりする。ややこしくなる。）

この辺はRubyやRails特有の話ではなくて、最近のLL Webのフレームはこれだ、でよいと考えています。PHPやNode.jsでも同じように通じる **基本** として伝えたい。

ということで激安インスタンスは不要です。そのためのインストールフォロータイム。で、フォローしきれなければ Cloud 9 へ。あくまでイベント時だけでなく、その後も **自力で継続的に使える方法を提供したい。** でないと学習を継続できないので。

**Comment by PharaohKJ** [comment]
それもすごい興味あるのでぜひそれをお願いします。私も習います。
