### ISSUE TITLE
平鍋さん招待プロジェクト

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#531]
- [x] そもそも本当に可能なのかを確認する
- [x] 謝礼周りを確認・調整する
- [x] 日程の候補を連絡する

それなりの広さの施設を抑える必要が出てくるので、早めの調整が望まれる。

**Comment by libero18** [comment]
平鍋さんに連絡しました

先ずはお話をしてもらうことができそうかの確認をしたところ、12/9の午後に金沢で
公演される予定が既にあるようで、その日の夜とか如何ですか？とご連絡頂きました

日程的に日が無いので、会場の手配とか考えると実施は難しそうな気もしますが、
先ずは検討可能なものとするため情報を共有します

**Comment by libero18** [comment]
追加の話として、先ほど連絡を頂いたのですが、前日でも大丈夫とのことです

**Comment by PharaohKJ** [comment]
早速連絡してくれてありがとうございます。

さすがに12/9夜開催では会場も押さえられないだろうのでちょっと無理になっちゃいますね。

@libero18 さんが個人レッスンを受けるついでに+数人、だったら有志を募ればいけるかもしれない
ですが、今回としては、やっぱり、前回(meetup #7) のようなスタイルでお願いしたいと
考えています。

そういうわけで、ワガママに、日を改めて前回と同じスタイルというわけにはいかないですか？
と打診してほしいです。

さすがにお立場やスケジュールなどあるでしょうから、「前回(meetup #7)のようにするってのは
今回は無理そう」ならば、残念ながらまたの機会にさせていただきましょう。

どうでしょ？

**Comment by libero18** [comment]
予約でいっぱいなこともあって会場の手配が難しいのはこの前の話で理解してるので、
日を改める前提で日程の調整をするなら土曜日に話した通り、先の予定として
2月から4月の実施予定で相談してみます

ふぁらお先生以外にも意見あるかもしれないので、少し時間をあけてから連絡しますね

**Comment by PharaohKJ** [comment]
はい。まあ、我々に一任されてるので、こっちで進めていいと思いますよ。

一応、呼んでおく。 @kanazawarb/owners 各位どうでしょ？

**Comment by izawa** [comment]
当初こちらで想定した範囲で調整する方向しかないんでないのかい？

**Comment by kiyohara** [comment]
平日の夜に実施というのは、kanazawa.rb の枠組みの中ではあり得ない選択肢のように思うな。
前回のブレストで出ていた日程候補の中から対応可能な日がないかを聞くのがよいと思います。

**Comment by libero18** [comment]
- [x] そもそも本当に可能なのかを確認する
    + ok
- [x] 謝礼周りを確認・調整する
    + 謝礼不要
- [ ] 日程の候補を連絡する
    + ２月〜４月の第３土曜日を候補として確認中
    + 第３土曜日が難しそうなら２月〜４月の他の土曜日で相談したいとも伝えてあります

**Comment by PharaohKJ** [comment]
お返事いつごろにいただけそうでしょう？最近の金沢の会議室状況からいって、急かして申し訳ないですけれど、いったんお返事今週いっぱいぐらいにいただけませんか、とか、打診していただけますか。

**Comment by wtnabe** [comment]
ずぇんずぇん手伝えず申し訳ない。

今ITプラザ武蔵の予約状況を確認したところ、幸いまだ第3土曜は空いてるけど、それ以外の土曜はもう難しそうなので、

**2月は調整不能**

となったようです。 **いったん2月の線はナシにして進めますか。** その方が分かりやすそう。

**Comment by libero18** [comment]
その後いかがでしょうか？の相談もしなければいけないので、それにあわせて
施設の予約状況的に2月は難しくなりましたと伝えることはできますけど、
ITプラザ武蔵じゃないとダメな理由ってありましたっけ？

特にここだって場所は無いですけど、別の場所を借りてそこでやるのも
選択肢としてはありなんですよね？

もちろん、ITプラザ武蔵でやれる方が望ましいし話をシンプルにしようと
考えるなら「2月はナシ」が良いのだけど、既に「2月を前提」に
調整されていたらどうしようかなと・・・・

なので、どのくらいのことまで想定して「2月はナシ」として相談するかだけ
事前に確認しておきたいです

単純に箱があれば2月でも問題ないよって話なら、手配可能な場所があるか
いつまでに確認して返事しますって答えれれば大丈夫なので
あまり気にしないでも良いかなと思うけど、ITプラザ武蔵を前提にしないと
ダメなら施設予約のカレンダーを見ながら相談しようと思ってます

**Comment by wtnabe** [comment]
や、分かりやすさとリスクと動きやすさで考えてるだけです。「こっち目線」で言うと、そもそも日程の選択肢として2つあって、

 1. Kanazawa.rbのレギュラーのmeetupのタイミング
 2. Kanazawa.rbのレギュラー以外の土曜

で、これに

 * 2〜4月という時期の選択が入り
 * かつ場所の選択肢が増えたり増えなかったりする

辺りがパラメータな訳ですが、平鍋さんから見た時に「2月は」「今なら」「第3土曜なら」オッケー、って分かりにくくねーかな？っていう辺りを危惧してます。もし思い違いが起きたらタイミング的に解消は難しいから。

もちろん、現時点で「不可能」という意味ではないです。

別会場については前回の meetup の時点で話が出ていなかったので、完全に頭から抜けてました。が、選択肢増やすのであればなおさら時間に余裕のあるタイミングで考えた方が負担が少なくていいんじゃないかと思います。今からだと特に会場手配が「勝負」になっちゃうので。

**Comment by libero18** [comment]
りょうかいっす

元々、会場の予約が先の予定じゃないと難しい状況は伝えてあるので、
状況が変化して難しくなったことを前提に話せばそっちはそれで良いとして、

仮に3月以降になった場合に2月はもくもく会とかやると思うんだけど
その時の場所って意味でいうと今のタイミングで空きのある部屋を
予約しておかなくても良いんだっけ？って問題は残るので、
そっちは別途、運営のメンバーで相談しないといけないねー

**Comment by wtnabe** [comment]
圧倒的そんながで :muscle:

**Comment by PharaohKJ** [comment]
:muscle:

**Comment by libero18** [comment]
開催を見込んでいた会場の施設予約について、空きが無くなり2月の予約が
難しくなったことを伝えました

そのうえで、調整を実施するため現在の状況をお伺いできますか？と
連絡いたしましたので、状況が分かり次第にでも情報共有します

**Comment by libero18** [comment]
2月なら今のところどこで大丈夫そうなので候補日もらえると〜ってお返事ありました

差し当たり、2月の会場の問題もあるのでまだ空いてるようなら2月の第3土曜日にビジネスプラザの予約を入れて
その日でお願いしますって連絡するのが良さそうな状況であります

会場の手配が難しければ、3月または4月の土曜日で改めて相談させて下さいって話にしてあるので、
会場が予約できなかったりしたら改めて調整します

**Comment by PharaohKJ** [comment]
んじゃそれで。

各位

- 日時
2月第3土曜日 (2/20) 13:00〜

- 会場
ITプラザ武蔵の会議室のどこか

で手配開始したいと思います。

上記日程でOKな人は :+1: お願いします。5票集まったら ITプラザ武蔵抑えてしまいましょう。
@kanazawarb/owners 各位投票お願いします。
@cottondesu 先生、申し訳ないけれど、5票集まったら連絡しますので、会場予約お願いします。
@libero18 先生も5票集まったら、2/20(土) 13:00〜 決行予定で連絡お願いします。

懇親会場は今月の kanazawa.rb で合議で決めましょう。どう宣伝するか、によってはちょっと
いいところとか抑えないといけないかな？と考えてます。

**Comment by kiyohara** [comment]
日程について、2月第3土曜日(2/20) 13:00〜 であぐりー :+1:

**Comment by izawa** [comment]
:+1:

**Comment by wtnabe** [comment]
:+1:

**Comment by libero18** [comment]
:+1:

**Comment by wtnabe** [comment]
えーとこれは5に達したということでいいのかな？

**Comment by PharaohKJ** [comment]
あと @cottondesu 先生のお返事次第ってことにしておきましょう。

**Comment by wtnabe** [comment]
5票とは、いったい

**Comment by cottondesu** [comment]
:+1:
ということで
ITビジネスプラザ武蔵 研修室1(50名)を2/20 午後(13:00-17:00)で予約しました。

**Comment by wtnabe** [comment]
:muscle:

**Comment by libero18** [comment]
まだ確定ではないですが、先ずは2/20（土）でお願いしました

お返事ありましたらまた共有しますね

**Comment by PharaohKJ** [comment]
:sushi:

**Comment by libero18** [comment]
- [x] そもそも本当に可能なのかを確認する
    + ok
- [x] 謝礼周りを確認・調整する
    + 謝礼不要
- [x] 日程の候補を連絡する
    + 2/20 (土) 13:00〜 で日程を抑えて頂きました

**Comment by PharaohKJ** [comment]
:muscle:

**Comment by cottondesu** [comment]
2月の施設料の支払が終わりました！！

**Comment by PharaohKJ** [comment]
当日の時間割を決めたいと考えています。

下記、運用ミーティング議事録より。

```
タイムスケジュールまずはこちらから提案する方向がよいのでは

自己紹介 30min
平鍋さんセッション 1hour
kanazawa.rb の誰か 1hour
この内容は来月に検討する
案は募集するのでみんな何か考えてきてね :)
次回のもくもく会で検討しても良い
```

@libero18 さん

いまのところ、案として、このような時間配分を考えているのですが、
いかがでしょうか。休憩、質疑あわせて120分ほど必要でしょうか？

と、お伺いしてください。

**Comment by libero18** [comment]
pullreq の #545 のコメントで確認した内容も含めて ↓ の内容で相談しとります

* プロフィールの画像について
  + こちらの画像を利用しても大丈夫でしょうか？: http://www.esm.co.jp/inside/inside01/#art1
* プロフィールの内容について
  + こちらの内容を利用しても大丈夫でしょうか？: https://anagileway.wordpress.com/about/
* セッションのタイトル
  + タイトルを教えて下さい
* セッションの概要
  + 概要を教えて下さい
* セッションの時間
  + ご希望のセッション時間がありましたら教えて下さい
     - 「今のところ適宜の休憩や質疑応答の時間も含めて、前回と同じ120分でお願いしたいと考えています」とは伝えてあります

ご回答がありましたら、 meetup のページに追記して pullreq します

**Comment by libero18** [comment]
120分でお願いします

座学60分、ワークショップ60分みたいな感じでやることになりそうです

携帯から&外出してるので取り急ぎ時間配分だけ
詳細に関しては、また別途連絡します

**Comment by PharaohKJ** [comment]
別途連絡を待ちます。ワークショップの内容次第ではタイトルを再考しましょう。

@kanazawarb/owners ちょっと先立って公開しようって話になってましたが、平鍋さんが
ワークショップやるとなると #545 の内容だと足りない感じなので、 @libero18 さんの
詳細待ちにします。

詳細いったん受け取ったら私が #545 をアレンジしてたたき台として出します。

**Comment by libero18** [comment]
+ プロフィールの画像について
    - [こちらの画像で確認しました: http://www.esm.co.jp/inside/inside01/#art1](http://www.esm.co.jp/inside/inside01/#art1)
+ プロフィールの内容について
    - [こちらの内容で確認しました: https://anagileway.wordpress.com/about/](https://anagileway.wordpress.com/about/)
        * ただし、長いので経歴とかは端折ってくださいとのコメントもらってます
+ セッションのタイトル
    - 「アジャイル時代のモデリング」
+ セッションの概要
    - 「モデリングのパワーを活かしながらアジャイルに開発を進める、軽量モデリングの手法とその事例についてお話します。」
+ セッションの時間
    - 時間については120分で（おそらく、座学60分、ワークショップ60分の内容）
+ ワークショップについて
    - 小さな問題をペアモデリング
        * 「ペアモデリングのワークショップを実施する予定がありますので、（可能な方は）astah community インストールしてきて下さい。」
            + これをイベントページに書いておく必要ある
        * 当日のインストール状況次第では紙と鉛筆で実施する
            + 参加者には、上記のように astah community をインストールしてきてもらうか、紙と筆記用具を持参してもらう感じでお願いする必要がありそう
            + 最悪、ITビジネスプラザには1階にコンビニがあるので忘れた人にはそこで買ってきてもらう方向で
                - 「ペアモデリングのワークショップで利用する場合がありますので、紙と鉛筆を持参ください」
                    * こんな感じでイベントページには書いといた方が良さそう

**Comment by libero18** [comment]
↑ これとは別の話としてタイムテーブルのことでひとつ気になったことがあって、
自己紹介をやること自体はとても良いと思うのだけど不確定要素が強すぎるので
予定時間内に終わらない可能性が高すぎると思います

なので、少し趣向を変えて前後の机(計6人？)をチームとしてお互いの自己紹介
および各自の考えてるモデリングとはなんぞ？を決められた時間までに
話し合ってもらって、そのうち3チームくらいをピックアップして発表してもらう

そこで時間が余れば追加で数チーム追加で発表してもらう感じのアイスブレイクをやって、
流れで平鍋さんに渡せれば少しは「モデリングとは？」って明確なイメージを
参加者各自が持って話が聞けて良いんじゃないかな？と思うんですが、どうでしょ？

**Comment by PharaohKJ** [comment]
全然別の話じゃなくて、議論した日には情報が無いから、とりあえずのタイムテーブルを出して、
ページを作ってしまおうか、お客さんこないと失礼だし、、、という話の流れです。

北陸の.NET勢の大型イベント日と被っちゃって今のところ早く公開しないとヤバイかなという感じ。

本格的にお願いすることになった結果、平鍋さんと @libero18 サンが相談して何か企画があって、
タイムテーブルできてきたのなら、ぜひそれでやりましょう。

- [ ] PR #545  のタイムテーブル、内容、経歴の端折などなど、書き換えてください。

まぁ私がつけたい文句は以下のあたりですが、マジでまかせます。

- 何人集まるかわからない（ @libero18 さんのいう不確定要素が強すぎ) のでチーム組む前提、てのはピンとこない
- モデリングとは何か？をプレゼンて提示された後にあれこれ議論するのはアリだと思うが、前に議論するてのはピンとこない。

インストール状況を見て紙とペンで〜　←　これも @libero18 サンのいう不確定要素でかすぎ
なので、これは先日のcode retreat時のように、

- 基本、紙とペンで行う
- 紙とペンを kanazawa.rb で参加人数分、用意する

ことで不確定要素無くす方向で検討しましょう。

- [ ] 紙とペン購入については1月の meetup でみんなに許可を得る

ということで進めます。

**Comment by libero18** [comment]
"PR #545 のタイムテーブル、内容、経歴の端折などなど、書き換えてください。" については
対応して pullreq するつもりではいますが、正直なところ "早く公開しないと" の事情と
紐付けられると困るので、いったん #545 で @PharaohKJ 先生が宣言してた "現在調整中" で
対応しといてもらえると助かります

「紙とペン」じゃなくて  「astah community」 を使ってやる前提の話だったんすけど
現地インストールしようと考える人らが必ず居るだろうと思い、

そのせいでトラブルになる可能性もあるから、そうなった場合は未インストールの
人には紙とペンで対応してもらうって話の流れになったこともあって、

提示された方法じゃなくて、最初から紙とペンを使う前提とするなら
いちおう再確認したりもしたいのでお願いします

あとは他の話として紙とペンを参加人数分用意するのは、持ち込むことや
持ち帰りとその後の取り扱いの問題もあるので、そこまで考えての話でしょうか？

ってのはあるので、もしそうするならレポート用紙とボールペンを
ノベルティとして作成し参加者に持って帰ってもらうことも考える余地がありそうです

**Comment by PharaohKJ** [comment]
> pull request するつもりではいるが、現在調整中で対応しておいてもらえると助かる。

↑それではもう私が全部「調整中」にして、日付だけ確定させてページ作ってdoorkeeperまで
作ってしまうので、どんどん修正していってください。

誰が何に困るのかピンときませんが、単に「早く決めて欲しい」と煽られて、平鍋さんが
困るだろう、ということならば、その担当の @libero18 さんの気持ちも含めてお察しいたしますが、

- 最近はどこもかしこも勉強会なので、このイベントが知られずに埋もれる
- 告知期間をとりたい
- 集客合戦において「内容調整中」というのは参加判断するお客さん困る

というのは避けたいのはお互いわかっていただけると思いますので、がんばってください。
(まぁ平鍋さんの名前出しておけば人集まるだろ？？？後でになってもキャンセルしてこっちくるだろ？
ってのはあるのかもしれないですけれどー)


>「紙とペン」じゃなくて 「astah community」 を使ってやる前提の話

どこまでが @libero18 さんの提案で、どこからが 平鍋さん の要求なのかがわからないですが、
平鍋さんのお立場を察するに、 「astah community」使うことが大事そうですね。

それでは調整中で作っておくので pull request に 「astah community」をインストールして
もってくる旨記載お願いします。

インストールしてこい、が守られなかった場合の、紙とペンについては、
別にノベルティとか考えてなくて、使い捨てで。

数百円あれば山程ペンと紙買えますし、次のkanazawa.rbで予算が取れ次第、私が責任持って用意、
持ち帰ります。

**Comment by PharaohKJ** [comment]
#108 もあって確認済んだので、とりあえず #545 マージして doorkeeper 公開してしまいます。
告知活動に入っていきましょう。 

@libero18 先生、詳細決めて、更新よろしくお願いします。更新があるたびに告知していきましょう。

**Comment by libero18** [comment]
平鍋さんの確認と修正の対応が終わったので、meetup 42 の告知して大丈夫だと思いまーす

**Comment by PharaohKJ** [comment]
:+1:
明日 @kiyohara 殿と相談するでござる。

**Comment by PharaohKJ** [comment]
@libero18 さん、ざっくりタイムテーブルが現在調整中でした。決めて記入してください。

**Comment by PharaohKJ** [comment]
#548 でタイムテーブル完了。

前回(meetup 7 2013/03)から2年たっていることもあり、 改めて質問、ディスカッションしたいこと
があったりすると思います。
そういうわけで、それをまとめて、パネルディスカッションしようかなーと思います。

- パネリスト決め(平鍋さん @libero18 @PharaohKJ か？)
- お題ぎめ
- そもそも他のイベントやりたい

ということを、次回の kanazawa.rb 41 で決めたいなと思います。

> @kanazawarb/owners 
他にやりたいことあったり、質問あったりしたらここに書いて下さい。
kanazawa.rb 41の議題にしたいと思います。

> @libero18 
平鍋さんに、連戦で申し訳ありませんがパネルディスカッションにご登壇していただけますで
しょうか？とお伺いしてください。

**Comment by cottondesu** [comment]
meetup41運用ブレストにてパネルディスカッション用の質問を募集することになったので
Doorkeeperの申し込み欄に パネルディスカッション用の質問(内容はアジャイルかモデリング)【任意】 の
項目欄を追加しました。

項目名が不適切の場合は変更してください。

**Comment by libero18** [comment]
平鍋さん、パネルディスカッションのパネラー参加OKとのことです

**Comment by PharaohKJ** [comment]
doorkeeperの42ページ、41の内容が抜けていたので(41開催前に作ったページだからしょうがない)
41のレポ・togetter・30daysへのリンク追加しておきました。

**Comment by kiyohara** [comment]
イベント終了に伴いクローズ
