### ISSUE TITLE
meetup42のパネルセッションでの質問

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#557]
何もなかったときのための質問。(たぶん当日ワークショップしたらでてくると思いますが)

1. 今回のastah* communityでUMLやりましたが、UML自体現場でどれぐらい普及していますか
  - 会場にも現場で使ってるかきく
6. ソースコード以外、複雑なもの（例えば、社内業務フローなど)にモデリングの活用事例はあるか
2. 通じればよいオレオレUMLはアリ or ナシ。
3. 開発者とそれ以外(例えば営業)のコミュニケーションにも使ったりしてる事例ありますか？
  - ソフトウェア開発以外にも事例とかあるのでしょうか？ 
4. わたし（加藤）の考えだと、こういうのでがんばって作り、それをもとにコードに落としていく、  
  というのはかなりウォーターフォール、なのですが、イテレーションの速度こそが違いなのか？
5. UMLというか、英語と日本語について。例えば請けた仕事をそのままモデリングしたら、普通に
  「お店」とか「社員」とか日本語がでてくる。
  最近の仕事で、英語に落としこむと顧客のシステム担当者と話をするたびに日本語に戻したり
  なんだりする必要がでてきてツライ。
  - モデリングは全員英語でやるしかない？
  - モデリングは通じればよくて、仕様書(納品物)としては用いない書捨て？

**Comment by libero18** [comment]
一応、個人的に感じたことをフィードバックしておきますが、
この内容を質問するのであればパネルディスカッションに
含められても自分は何も議論できないっすよ

以前にも言ってたと思いますが、「アジャイル」がテーマのことなら
良いけど「モデリング」に関しては無理ですよって話です

もう少し言うと、パネルディスカッションに参加する人って
どうなるのかわからないけど、1の質問みたいに
「これ平鍋さんしか答えられなくね？」ってテーマは色々と困るかも

2と4って同じじゃない？と思ったりもするので4はこんな感じで
少しだけ修正したいけど、2と3と4みたいな話は面白いよね

+ 開発者とそれ以外(例えば営業)のコミュニケーションにもアジャイルの手法を使ったりしてる事例ありますか？


アジャイルをテーマにしたものがないので付け加えるなら

+ アジャイルをやってて良かったことは？
+ 逆に苦労したことは？
+ どんなことから導入を始めた？
+ やってみたけど失敗したプラクティスは？
+ 逆に今後もやり続けたいプラクティスは？

こんな感じのことを聞くとお手軽に答えれるので
アジャイルにチャレンジしてる人なら議論はできるんじゃないかな？と思う

**Comment by PharaohKJ** [comment]
まぁ流れで話題提供できりゃいいと思いますし、
シーンとなるのがアレなだけなので1時間埋まる話題が
あればいいと思いますよ。

僕はりべろ氏の話題でもいけるので他から特に意見がなければ
りべろ氏の話題でいきましょう。

✉︎ from iPhone

2016/02/19 19:05、Ryuichi Nakajima <notifications@github.com> のメッセージ:

**Comment by wtnabe** [comment]
「コミュニケーション」に寄せることで「アジャイル」にも「モデリング」にも振りやすいし、むしろ「アジャイル」に寄せすぎない方が1stセッションからの繋がりはいいんじゃないかなーと思いますよ。細かい表現にこだわらなきゃ結局似たような話題になりそうだし、そんなに心配しなくていいんでない？と思いました。

**Comment by libero18** [comment]
あー なんか書き方が良くなくて誤解されてるかもしれないと思ったので、
捕捉しとくと、モデリングの質問だけだと全然参加できない置物になって
困るのでバランスをみてアジャイルの質問も少しは追加してね

って話なのです

アジャイルに寄せて欲しいって趣旨ではないので、モデリングのことは普通に質問したら良いと思います

**Comment by kiyohara** [comment]
イベント終了に伴いクローズ
