### ISSUE TITLE
gh-pages Jekyll 3.0対応

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#560]
下記対応をしましょう。

- [ ] Textile を完全廃止（期限は 2016-04-30）
- [ ] Gemfile を `gem 'jekyll', '> 1.0'` となってるのを `> 3.0` にして動作テストなどなどする

参照したネタは以下。

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

> Two additional changes
> 
> The Jekyll 3.0 upgrade will introduce two additional changes that may affect a small subset of users:
> 
> Jekyll no longer supports relative permalinks. This has been the default since Jekyll 2.0, and is only an issue if you explicitly added relative_permalinks: true to your site's configuration. Going forward, regardless of your site's configuration, if you add the permalink directive to a page's YAML front matter, the path should be relative to the site's root directory, not the page's parent.
> 
> Starting May 1st, 2016, GitHub Pages will no longer support Textile. If you are currently using Textile (Redcloth) to author your Jekyll site, you'll need to convert your site to use Markdown instead.

**Comment by cottondesu** [comment]
* meetup42のレポートページをreport.mdに変更しました。

**Comment by kiyohara** [comment]
おおー、さすが @cottondesu 先生。早速対応ですね。
既存のやつもなんかコンバーターとかあれば良いんだけどね。
ありそうだなと思いながら調べずに書いてる。どこかで探してみようっさ。

**Comment by wtnabe** [comment]
これ、Textile廃止以外は影響ないって見ていいんかな？ Textileの話だけであれば、title変えてよい？

**Comment by wtnabe** [comment]
titleから内容が推測しにくかったので変えちゃいました。ゴールは Jekyll 3.0 対応でいいよね。個人的には次回もくもくのテーマにちょうどよさそう、なんてことを思いました。

Markdown化については、HTMLから逆変換が可能なツールは多いので、

 1. buildして HTML を生成
 2. HTML → Markdown変換
 3. 必要な整形

みたいな流れでイケそうな気がします。

**Comment by PharaohKJ** [comment]
仕様変更に追従しないといけないね、というissueであって調査してたら他にもあったからまた内容が不正確だからtitleなおそうってなっちゃいませんか。
まぁならないだろうからこのままいって、なんかあったらまた別issueおこすって感じでやりましょう。

✉︎ from iPhone

2016/02/24 10:11、wtnabe <notifications@github.com> のメッセージ:

**Comment by kiyohara** [comment]
gh-pages の動作変更に追従するために jekyll 3.0 対応以外のことをしなくてはいけなくなる可能性は高いと思うので、加藤さんの言わんとするところはわかる派。
まあ、実質的に jekyll 3.0 対応だけすれば十分だろうとは思うので、

> まぁならないだろうからこのままいって、なんかあったらまた別issueおこすって感じでやりましょう。

これで。

**Comment by wtnabe** [comment]
内容が曖昧ならやることの洗い出しIssueと片付けるIssueを分ければいいかなと思いました。

もしアレなら、こっちをメタIssueにして

 * 仕様変更の影響範囲調査
 * それぞれ対応

みたいに分けてもいいと思います。なんならそういうmilestoneを別に起こすとやりやすいかも。

とは思うんだけど、Issueのtitle見てもやることがよく分からないんだけど、なんかもうやること決まってるみたいだし、「これじゃダメなん？」てのがいちばんの理由っす。とりあえずmilestone切りますか。

**Comment by kiyohara** [comment]
> まぁならないだろうからこのままいって、なんかあったらまた別issueおこすって感じでやりましょう。

とりま、このまま進めればよいと思いますよ :)

**Comment by wtnabe** [comment]
ありがとう。ゴールを明確にしたかったのねん。

**Comment by PharaohKJ** [comment]
これ、次回(meetup44)でもくりましょう。

**Comment by PharaohKJ** [comment]
`rake new_meetup` でいろいろ最低限追加する機能をふやす。

**Comment by PharaohKJ** [comment]
https://github.com/kanazawarb/meetup/tree/feature/textile-to-markdown

`pandoc` で変換したものをいったんおきました。が、

- 先頭付近にある Jekyll の属性指定記述 `---` が HR にされてしまう
- テーブルがまともに変換できてない
- 埋め込みリンクがまともに変換できてない
- クロスハッチや記号？の前に謎のエスケープ `\` が入っている

です。とりあえず、30日まで時間もないんで 少しづつ修正してマージしていきましょう。

修正担当が重複すると寒いんで、やる前はここで声かけてやりましょうか。

**Comment by kiyohara** [comment]
とりあえず、手元に確認用の環境は作りました。
アップデートするときは声かけしますね。

**Comment by kiyohara** [comment]
#584 を無事にマージしたことで、対応完了。
.textile はなくなったよ。

クロスチェックの目は一杯欲しいので、変なところを見つけた人は Issue 化だけでもよろしくお願いいたします。

@PharaohKJ サン。やりきったな！( •̀ㅂ•́)و
