### ISSUE TITLE
無線LANアクセスポイントを買う

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#561]
- [x] @cottondesu 先生の会計報告を元に予算を決める
- [x] 商品を決める。25台同時接続できるといいな。
- [x] 1台だけだと持ち主がmeetupにこないと受け渡しが発生しちゃうから、複数買って何人かにもたせることにしよう
  - [x] 台数を決める
  - [ ] 所持者を決める

**Comment by PharaohKJ** [comment]
http://faq.buffalo.jp/app/answers/detail/a_id/326

バッファロさんの 50台同時接続法人用って3万ぐらいするようだ。

http://www.apple.com/jp/airmac-express/

私が提供しているAirMacは11,200円。対応人数は50人とのこと(仕様より)

@kiyohara さんの今提供してくれてるやつはいちおう公称値ってあって実績あるのかな？
それが安ければそれを買えばいいんじゃないかなーと思ったり。

http://ascii.jp/elem/000/000/889/889452/
http://pctsuhanmax.com/net/mobile/

比較記事あるけどどれも古い & 結局何台ぐらいまでいけるかってのはピンとこないね。

3,000円ぐらいのモバイルは4台以下推奨。
1万円しないぐらいの普及用無線LAN家庭用は15台ぐらい。
数万円の法人向けで50台。
AirMacは50台といっている。

といったあたりか・・・。予算次第ですかね。

**Comment by cottondesu** [comment]
2016/2/21 現在のKanazawa.rbの資産は66,514円です。
meetup43にて資産からどれだけを物品購入の予算にするのか
話し合いましょう。

**Comment by PharaohKJ** [comment]
ok, グッズもね。

**Comment by tokkie07** [comment]
家に使ってない無線ルーターでpa-w500p-bってのがあるので、それでよかければ持って行きます。
一応接続数は10台まで推奨のやつですが。

**Comment by kiyohara** [comment]
自分が持って行ってるのは Logitec の LAN-W300N/RSB ( http://dl.logitec.co.jp/index.php?pn=LAN-W300N/RSB ) ですね。ホテル無線の触れ込みで出たヤツで、かなり古い。推奨台数についての記載は見つけられなかった。

コレを選んだポイントは持ち運びが楽というトコロ。
スピーカーなんかも一緒に持ち込んでるので、軽くて小さいのが良かったのよね。

**Comment by cottondesu** [comment]
meetup44の施設料を支払ったので
2016/3/10 現在のKanazawa.rbの資産は62,214円です。

**Comment by cottondesu** [comment]
meetup43で決まったこと
- AirMac Expressを1台購入する。
  - PharaohKJ さんが一旦立替えて1台を購入する
  - 翌々月(5月)にKanazawa.rbからお金を渡す

残課題は所持者を誰にするかはmeetup44で決める。

**Comment by cottondesu** [comment]
PharaohKJ さんがAirMac Expressを購入してくれたので
立替えてくれた購入金額12,096円をお渡ししました。

所持者を誰にするかはmeetup44で決める。

**Comment by kiyohara** [comment]
@cottondesu @PharaohKJ 対応、マジ感謝っす。物品管理袋用意すると良いかもねって話も出てたので、その辺と合わせて次回 meetup の時に検討しましょう。（次回は参加できるよ！ (^_−)−☆

**Comment by PharaohKJ** [comment]
土曜日に @cottondesu さんから、会計袋受け取りまして、トートバッグに入れました。

**Comment by PharaohKJ** [comment]
今後、トートバッグに入れて、会計袋と共に持ち歩く運営ということにしました。

で、誰がトートバッグを持ち歩くのか、についてはまた後日議論。
