### ISSUE TITLE
ToDo 管理として Github Issue からの移行を検討する

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#576]
以前から、 Github Issue で ToDo 管理するのには課題があるという認識は共有出来てると思っている。
主に、繰り返しの登録がだるいって話と、DueDate が設定できなくて通知も来ないのツライって話。
まあソースコードの編集に紐付く Issue のためのものだからね。
運用のための設計はされてないのが当然と言えば当然である。

なので、ToDo 管理としてよりよいものがないか、少し探してみたいと思ってます。
要件としては以下ぐらいが上がっていたと思う。
- 広く公開され、誰でも ToDo の状態を確認出来ること
  - 特定のサービスを使うにしても、そのサービスに「登録」しないと見られないとかはダメ
  - これは kzrb の大切な運用ポリシーとの認識
- ToDo に紐付いて、サービス上でディスカッションができること
  - 担当を設定できるならなおよし
- 締め切りを設定できること
  - 締め切り前に通知がくるとなおよし
- クローズした ToDo も後から見返すことができること
- なんらかの状態変更があったときに通知がくること
  - チェックボックスの ON/OFF レベルで通知が欲しい
  - 「だれが」変更をしたかがわかるとベター
- ToDo セットを再利用できること
  - おもに meetup 毎の運用のため
  - バッチ的に登録できる場合でも「特別なツール」が必要となるのは避けたい

とりあえず、最近よく見る Trello に環境をつくってみた。

https://trello.com/b/cYkRHoSO/meetup

Public 設定にしてあるので、誰でも見られるし、参加もできるはず。
通知を受け取るためには、サービス登録＆参加しないとダメなのは、一つの敷居か。
Github のアカウントでログインできればだいぶ楽なのになー。

---

と言うわけで、試験的に Trello で ToDo 管理してみるよ。
あくまで試験運用なので、現行の ToDo マスタは Github Issue です。
使い勝手のレポも含めてどこかで報告＆相談します。

---

なお、個人的に Activity 見るのにつかってる Slack にも連携させておいた。

https://kzrb.slack.com/messages/todo/

興味ある人は Invite しますよ。
idobata はごめん、連携の方法調べられてないっす。
「Trello でいいじゃん」ってなったら考えます。

**Comment by kiyohara** [comment]
Trello はかなり良い感じなのだけど、Trello ユーザーでないとコメントができないってのが、協力者の足かせになりそうな気配を感じる。
一方で Github なら、kzrb の運営を手伝ってくれるって人なら多くの場合すでにアカウントを持ってるであろうことを期待できる。
悩ましいところだけど、現状だと Github Issue の方を選んじゃうな。僕なら。
もう少し別の物がないか調べてみます。優先順位低めで。

**Comment by PharaohKJ** [comment]
あー確かにログインしないと何も書き込みできないんだね。

Googleアカウントでログインだけじゃなくて twitter 、 GitHub あたりもあればよかったんだろうけど。

**Comment by kiyohara** [comment]
めも。

meetup 48 の運用ブレストで kiyohara が「定型的なものに限って Trello にしない？」という提案をした。
メリットデメリットがわかりにくいのでプレゼンして欲しいという話になった。
kiyohara がんばれというステータス。

**Comment by kiyohara** [comment]
めも。

まったく進捗してないのでアレですが…

スーパーハッカー @shirokuro331 さんが提唱する Asana ( https://asana.com/ ) を評価してみるのはありだと思った。

**Comment by shirokuro331** [comment]
> 特定のサービスを使うにしても、そのサービスに「登録」しないと見られないとかはダメ
Asana、これ以外は要件満たしてるかと。

**Comment by kiyohara** [comment]
いろいろ検討したけど、アカウント登録なしでも状況を公開できる ToDo 共有ツールを見つけるに至らなかった。
Github Issue で運用継続するものとしてクローズする。

ただし、 Github の Issue 管理のしかたについて改善は検討する（たとえば Github Projects の利用等）
