### ISSUE TITLE
elastic勉強会

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#610]
JAWS-UG 金沢 との連携
 - 相羽さんに、共同でどうか？という話、OKをいただいた

FB で 担当様に声をかけます。

**Comment by kiyohara** [comment]
現状を確認させてください。

* JAWS-UG 金沢 & Kanazawa.rb の共催で
* 9月を目標として
* elasticsearch をキーワードとした勉強会を開く
* 内容としては
  * elasticsearch のエバンジェリストさんに話をしてもらうことは決定
  * プラスアルファ（たとえば、地元スピーカーを擁立するか、とか）はまだこれから調整
* 次のアクションとしては
  * @PharaohKJ さんが elasticsearch のエバンジェリストさん側の要望等をヒアリングする
  * 他の人が出来ることは今のところない

との認識であってますか？

**Comment by PharaohKJ** [comment]
あってます

2016年6月20日(月) 22:15 Tomokazu Kiyohara <notifications@github.com>:

**Comment by hirolovesbeer** [comment]
横から失礼。

https://info.elastic.co/JapanLocalPage_page.html
須田さんなら直に連絡取れるしお願いも可能ですよ。

須田さんがCitrix時代からの知り合いなので結構付き合い長いです。

**Comment by PharaohKJ** [comment]
@hirolovesbeer あなたが神か。
とりあえず、meetup開催希望受付メールアドレスを別ルートで手に入れたのでそっちにもメール送りました。(須田さまには、その旨同FBメッセージ済み)

**Comment by kiyohara** [comment]
@PharaohKJ 
> あってます

了解っす ( •̀ㅂ•́)و

**Comment by hirolovesbeer** [comment]
須田さん宛てなら、cc: 阿部とか入れておいて、IIJの阿部の知り合いだよー、とか言ってみてくださいw

**Comment by kiyohara** [comment]
@PharaohKJ さんが繋がった elasticsearch のエバンジェリストと @hirolovesbeer さんの知り合いが同一人物だったって話か。縁を感じる。繋がるものですな。。

**Comment by PharaohKJ** [comment]
@hirolovesbeer さんも登壇した Kanazawa.rb だぜ？ってアピっておきました。ありがとうございます！！

**Comment by PharaohKJ** [comment]
須田さまからいいお返事いただきました。エヴァンジェリストの大谷さまがいらっしゃるそうです。
調整進めていきます。 @hirolovesbeer さんありがとうございました。

**Comment by PharaohKJ** [comment]
9/8(木)〜9/10(土)にRuby-Kaigiにでられるそうで、そのあたりでどうか？と調整中。
@kanazawarb/owners Ruby-Kaigi行く人いる？あと、ご希望あれば一応ここでお知らせ下さい。

**Comment by kiyohara** [comment]
@PharaohKJ 「そのあたりで」というのは、 Ruby-Kaigi に連結して 9/7(水) or 9/11(土) あたりでという話なのかしら。それとももっとざっくりと9月の1,2,3 週のどこか、とか、それぐらいの話なのかな？

ちなみに Ruby-Kaigi には行け^h^hかないです。
参加する人がいるか？というのは、その日程は外すようにするよって話かな？
須田さんも Ruby-Kaigi にでるということだから、ぶつかることはなさそうだけど。

**Comment by PharaohKJ** [comment]
9/10は土曜日(Ruby-Kaigi最終日)、9/11は日曜日です。おもいっきりぶつかってます。

そういうわけで、つまり、いつか？というのを相談中。でてる話としては以下

- 土曜を希望するが、平日になりそうか？
-  9/10(土)はRuby-Kaigiとかぶってるがその日を希望してもよいか？
- JAWS-UG金沢勢は 9/10ならOKだが翌週となると結構ダメなメンツがいる。

**Comment by kiyohara** [comment]
第三土曜という意味で 9/17(土) を希望としてあげるのがいいのでは？と思う。
Ruby-Kaigi とからめるのは、その方が須田さんがうれしくなるという話？我々がうれしくなるという話？

**Comment by PharaohKJ** [comment]
再度まとめますと

「9/8(木)〜9/10(土)にRuby-Kaigiにでるので、そのあたりに金沢でイベントをやるというのはどうか？」と打診を受けたので

加藤としては
「平日ではなく、土曜日を希望したい。 そのあたり、とおっしゃっているが、9/10(土)はRuby-Kaigi最終日である。この日、金沢にいらっしゃるということか？」

と返信したが、まだお返事はいただけていない。

JAWS-UG金沢 の連中に、希望日をヒアリングしたところ、 9/10(土)ならば集まれるが、翌週となると参加不可だと数人から連絡をいただけている。

Kanazawa.rb の連中に、希望日をヒアリングしているつもりだが集まっていない。 

という状況で、須田さんがうれしいかどうかはまだ全然わからないです。おそらく先方
打ち合わせ中だと思われます。

**Comment by kiyohara** [comment]
> 「9/8(木)〜9/10(土)にRuby-Kaigiにでるので、そのあたりに金沢でイベントをやるというのはどうか？」と打診を受けたので

先方から話をもらったという話なのね。すごく納得しました。
こっちから提案したという話だと思ってた。

**Comment by PharaohKJ** [comment]
ごめんて

**Comment by kiyohara** [comment]
いいのよ

**Comment by PharaohKJ** [comment]
9/11(日)ではどうか？とお返事いただけました。
(先方からの提示はいったんは 9/12(月) の午前中だったのですが、集客と会場手配が難しいと
お伝えしたところ 9/11(日)となりました )

会場にはDさんの新オフィスをお願いしようかなと考えていて、いろいろと集客の面、会場の面で手配したいと思いますが、いったんとりあえずアンケートとして、
@kanazawarb/owners  みなさんいかがでしょうか？日曜は出席難しいですかね？
それだったら月を改めるとか、いろいろあると思いますがいかがでしょう？

**Comment by izawa** [comment]
僕は日曜日でも参加できると思う。家庭、とくに子供がいるひとがどうかしら？

**Comment by kiyohara** [comment]
予定は入ってるけど、だいぶ先って話と多少動かしやすい予定ってこともあって、参加出来るようになる可能性はそこそこある感じです。

**Comment by cottondesu** [comment]
私も参加出来ます。

**Comment by cottondesu** [comment]
あっ、すいません。
9/11(日)は15:00まで用事がありました。
本当すいません。

**Comment by PharaohKJ** [comment]
@cottondesu さんには申し訳ないけれど、 9/11(日) に決定いたします。
elastic社さまにはその日程でOKを連絡いたしました。

会場手配に動きたいと思います。

**Comment by wtnabe** [comment]
:+1: (ばたり)

**Comment by bemarble** [comment]
@PharaohKJ さんに調整いただいてる会場についてもろもろ確認しました 👍

**Comment by PharaohKJ** [comment]
@bemarble さん確認ありがとうございますよろしくお願いします。

さて、先方と内容について詰めはじめました。以下のような感じで進めようと思っています。

- 特に詳しく説明してほしいこと
- 質問付にしたいこと
- 他やってみたいこと

など、 @kanazawarb/owners 各位ご連絡ください。いったん、火曜朝に先方に送付したいと思います。

```
13:00 - 開場 
13:15 - 挨拶 & 自己紹介
13:30 - セッション1
14:15 - 休憩

14:30 - セッション2
15:15 - 休憩

15:30 - セッション3
16:15 - 休憩

16:30 - セッション4 (LTかパネルディスカッションか)
17:00 - クロージング、解散
```

**Comment by PharaohKJ** [comment]
`elastic search` と `kibana` で、先方に送付いたしました。
8月入ったら、もう集客ページ作りたい、とあわせて提案しました。

**Comment by izawa** [comment]
@PharaohKJ セッション1〜3がそれぞれ45分ですが、誰が(どこのコミュニティ代表が)喋る、みたいなの想定ありますか？

**Comment by PharaohKJ** [comment]
@izawa いまのところ、まだありませんが、先方に kibana と elastic search はいったんお願いしてあるので

セッション1: elastic社さまによる elastic search
セッション2: elastic社さまによる kibana
セッション3: kzrb、jaws-ug金沢の各メンバーによる事例紹介（20分ずつとかか)
セッション4: セッション3のメンツ + elastic社さまによる 質疑パネルディスカッション

こんな感じでどうでしょうかねえ。といっても3はメンツが用意できまるかにかかってきますね。

@kanazawarb/owners 各位どうでしょうか？
JAWS-UG金沢のほうにもあたってみます。

**Comment by kiyohara** [comment]
えらすてぃっくさーちと言えば、 @hirolovesbeer さんという印象がある(・∀・)
kzrb 枠で話してもらえないかって事ですよねー

**Comment by izawa** [comment]
説明ありがとうございます。
(すでに声がけが始まっていますが)
kzrbとJAWS-UG金沢それぞれで人がassignできるとバランス良いですね。

**Comment by kiyohara** [comment]
確認なのですが、9月の meetup はどういう位置づけになるのかしら。

* 9/11 が meetup 49 で、内容が elastic な感じになる
  * jaws と合同でやるイベントを meetup の一部とするのは以前にもやってる
    * http://kzrb.org/meetup/34/

* 9/11 とは別に meetup 49 をやる
  * 第三土曜日は 9/17

このどちらかだと思うのだけど、 meetup 47 でそういった話って出ました？

ちなみに個人的には meetup 49 = elastic 回でいいと思ってます。
定期開催（第三土曜日）からはズレるけど、ま、そんなものじゃないかな？っていう。

**Comment by PharaohKJ** [comment]
私も meetup 49 でよいと思いますがどうでしょうか？

2016年7月19日(火) 14:56 Tomokazu Kiyohara <notifications@github.com>:

**Comment by izawa** [comment]
運営のコストもありますし meetup 49と兼ねる方向で良いと思います。

**Comment by hirolovesbeer** [comment]
なんか呼ばれたような気がしましたが、最近はElasticSearchやKibanaを触っておりません...ごめんよ @kiyohara

**Comment by cottondesu** [comment]
奇遇にもまだ9月の施設予約していないので、meetup49と兼ねる方向で良いと思います。

**Comment by kiyohara** [comment]
なるほど。んでは、 meetup49 という認識でいます(๑•̀ㅂ•́)و✧

@hirolovesbeer 別に *最近* 触ってなくてもいいと思うですよ？（キラキラした目

**Comment by hirolovesbeer** [comment]
@kiyohara 氏に口説き落とされたので、LT & パネルで参加する方向で調整しております。

**Comment by kiyohara** [comment]
ヤッタネ！ 👍

**Comment by izawa** [comment]
:+1: 忙しいときに、ありがとうございます！

**Comment by kiyohara** [comment]
> セッション1: elastic社さまによる elastic search
> セッション2: elastic社さまによる kibana
> セッション3: kzrb、jaws-ug金沢の各メンバーによる事例紹介（20分ずつとかか)
> セッション4: セッション3のメンツ + elastic社さまによる 質疑パネルディスカッション

以前に LT してもらった Interop のログまわり（kibana + elasticsearch）の話を再演してもらえたら嬉しいです！という話をしてました。
というわけで、 kzrb 枠＋パネル人員は、確保出来そうという見通しですね。

**Comment by hirolovesbeer** [comment]
妻臨月な感じなので、急に子供が...とかなった時は勘弁してください...

**Comment by PharaohKJ** [comment]
わかりました。それでは急なことにそなえて保険を手配しますのでぜひお願いいたします。

2016年7月22日(金) 10:09 Hiroshi <notifications@github.com>:

**Comment by hirolovesbeer** [comment]
ほーい、ネタは昨年のInteropでNagios Log Server(Kibana + ElasticSearch)を使った話になると思います。

**Comment by PharaohKJ** [comment]
:+1:

2016年7月22日(金) 10:17 Hiroshi <notifications@github.com>:

**Comment by PharaohKJ** [comment]
@kanazawarb/owners 各位進捗報告です。以下内容で問題がないか  meetup48 でお話していただきたいです。問題なければお手伝いよろしくお願いします。

## 日程の調整
9/11(日)で確定済み

## 会場の手配
DMMさま南町オフィスで済み
だが、日曜なので裏口から入らねばならぬ

## 懇親会手配
8月中に予約予定、予算5,000円

## 内容

- セッション1 - 2 : Elastic社 大谷さまによる Elastic Stackの紹介
- セッション3-1: kzrb @hirolovesbeer さんによる事例紹介(20分)
- セッション3-2: DMMさまによる事例紹介 (20分) (皆川さま経由で打診中、バックアッププランとして @PharaohKJ による「やってみた」
- セッション4: セッション3のメンツ + elastic社さまによる 質疑パネルディスカッション

3-2は確定次第、更新でお願いします。

## 各募集やページ
来週中に募集開始 &宣伝開始を 上記設定で行って欲しい、手伝って欲しいです。文面など、困りましたら @PharaohKJ までお願いします。

**Comment by kiyohara** [comment]
@PharaohKJ 本件、話をしておきました。ただ、裏口になるって点は話し忘れた(^^; 一応ご報告。

**Comment by kiyohara** [comment]
問題あるって声は出なかったので、お手伝いできそうな人は手を上げてくれる、はず。
自分も出来る範囲でやるよー

**Comment by kiyohara** [comment]
@PharaohKJ セッション 3-2 ってどんな状況でしょう。

**Comment by PharaohKJ** [comment]
DMM.comラボ様に打診中ですけど、今週中に回答なし、だめそうなら私がJAWS-UG金沢としてやってみた系を話しようと思ってます。

2016年9月1日(木) 13:49 Tomokazu Kiyohara <notifications@github.com>:
