### ISSUE TITLE
Doorkeeper 有料化対応

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#624]
Doorkeeper が有料になるので、イベント管理サービスを今後どうするか検討が必要。

[Doorkeeper料金体系の変更について \| Doorkeeper](https://www.doorkeeper.jp/news/2016/7/25/change-in-pricing)

[料金プラン \| Doorkeeper](https://www.doorkeeper.jp/pricing)

月額料金はざっと目を通した。
詳細（誰が、なに単位で払うのか、とかとか）までは確認してない。
たぶん、コミュニティ毎の設定にクレカでも登録するんだろう、とは予想している。

少なくとも 2016/08/31 までに結論を出す必要がある。
1ヶ月ちょっとか。

**Comment by PharaohKJ** [comment]
こ、これはツライ。30daysすらいただいているという状況において。

私としては、会場費にマシてもいいので支払っていいんじゃないかと思います。

ここから他に移動してもそこが無料をキープできなくなってまた引越し先を検討することになるだろうので、
いったん様子みながらここを使い続けるというのもよかろうと考えます。

**Comment by cottondesu** [comment]
今後もdoorkeeperを使う場合、毎月の固定費(施設料+doorkeepr料金)のアップは
一旦別の問題として置いといて、一番の問題はdoorkeeper料金支払で使う
クレカどうするか問題ですよね。

**Comment by kiyohara** [comment]
クレカ問題は確かに。
パッと見たところ「コミュニティオーナー」という立場の人が設定するものらしい。
kzrb のコミュニティオーナーは @libero18 さんですね。
譲渡できるのかも含めて要確認かな。

Doorkeeper に陳情書を出してみるのもひとつかなと思ってます。
非営利のコミュニティ活動に使ってるのだけど、なんとかなりませんか？的な。

もう少し、情報を集めるところからですね。。

**Comment by kiyohara** [comment]
[主催者の皆さまにご利用料をお支払いいただく理由 \| Doorkeeper](https://www.doorkeeper.jp/news/2016/7/25/why-charge-organisers)

> 模索していくうち、Doorkeeperを使ってくれる主催者の大半は、そのイベントへの参加費で儲けようなどとは考えておらず、前払い制イベントを開催することにそれほど関心がないことに気がつきました。

> この決定が、イベントで儲けようなどと考えておられない方や、コミュニティのためにイベントを開催している方にとって、決して納得のいかないことだということは十分に理解しています。

ツラいなぁ…

「非営利のコミュだからなんとかなりませんか？」って線で陳情書を書いてみようかと思ったが、これは無理だな。

**Comment by libero18** [comment]
管理者リストに含まれているアカウントであれば
コミュニティオーナーの権限は移譲できますので、
誰に移譲するか決めてもらえれば対応します。

自分には管理者と違って「何が」できるのかわからないのだけど、
たぶんクレジットカードの登録をする管理機能が
利用できるとかだと思うので、今後も使い続けるかどうか？
とは別に、もう少し実態にそってコミュニティオーナーの権限は
早めに誰かへ移譲しておいた方が良さそうですね。

**Comment by kiyohara** [comment]
@libero18 なるほど。
いろいろ調べてるところなので、一旦きよはらに譲渡してもらって良いですか？ :)

**Comment by libero18** [comment]
@kiyohara 移譲しておきましたよー

**Comment by kiyohara** [comment]
@libero18 あざまーす。みてみまーす。

**Comment by libero18** [comment]
@kiyohara たぶん管理者のところから、コミュニティオーナーの権限を
移譲できるのと、支払いのところを変更可能ってくらいが
管理者との違いかと思います。一応、確認できた話として共有しときます。

**Comment by kiyohara** [comment]
@kanazawarb/owners 本件、弊社の経理に掛け合ったところ「スポンサーとしてサポートしてもよい」との言を取り付けました。

http://blog.jnito.com/entry/2016/07/26/075226 この記事、特に記事の後半のスポンサーの下りを参考に社内展開してみた結果です。

というわけで、支障なければ弊社からのサポートで Doorkeeper 運用費をまかなうという選択肢が生まれた状態です。

センシティブな話なので、次回 meetup の場で直接話をしつつ結論を得たいと考えています。
Doorkeeper 有料化の期限もありますので、meetup では「結論」を得たいところです。
とはいえ、参加できない人もいると思うので、本スレッドにコメントを書いてもらえると嬉しいです。

**Comment by kiyohara** [comment]
本件、一旦 運営費用でまかなう対応としました。
クレカ登録まわりは kiyohara が対応します。
kiyohara が毎月 kzrb のキャッシュからお金いただく形ですね。
多少面倒そうなので、何回分かをまとめて請求とかにさせてもらうかも。
