### ISSUE TITLE
Slack の参加自動化の検討

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#627]
希望者がだれでも自由に kzrb.slack.com に参加出来るようにする。

**Comment by PharaohKJ** [comment]
今は参加したい人のメールアドレスをヒアリング → OKだったら管理者が invite って手順なんだっけ？

**Comment by kiyohara** [comment]
そう。
でも我々としてはオープンでいいと考えているので、ノーチェック＆自動で参加出来るようにしたい。
むらのさんが [rauchg/slackin: Public Slack organizations made easy](https://github.com/rauchg/slackin) ってのが使えそうって提案してくれたので、そのまま評価もお願いしている感じ。

**Comment by PharaohKJ** [comment]
なるほど。じゃあそれ待ちでよろしくお願いします。

2016年8月21日(日) 1:28 Tomokazu Kiyohara <notifications@github.com>:

**Comment by PharaohKJ** [comment]
https://www.npmjs.com/package/serverless-slack-invite-api

こういうのもみつけた。

**Comment by kiyohara** [comment]
@t-murano 先生のご尽力により slackin が導入されたのでクローズ
