### ISSUE TITLE
会場LocaLaboさま検討

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#719]
私の進捗報告 & メモ用 issue 。

55回ブレストログより

```
加賀温泉で合宿とか？
加賀温泉周辺でのイベントはそもそもそういう用途に使える場所があるのか問題

加藤さんの知り合いがそのあたりにコミュニティスペースを作ったらしい

ろからぼ たきがはら ( https://www.facebook.com/localab.takigahara/ )
インターネット回線はあるらしい

```

現状のアクションとしては @PharaohKJ が

- LocaLab さんに、Kanazawa.rb と ふくもく会 で使うとしたら貸してくれる？施設情報教えてくれる？　旨いったん伝えた。
- ↑についてLocaLabo さまと wiki にある会場情報をベースに3月内に一度打ち合わせ予定。無理そうなら4月予定。さすがに6月開催とか狙うなら4月のmeetupには検討情報を出したい。

以下 slack でちょっとでたネタ(打ち合わせ時に出すつもり)

- LocaLab を使うメリットがどの程度あるか。「温泉」ってレジャーとしてのメリットが際立つので、あーって感じだけど。
- 地理的に、金沢と福井の中間であるというのがモチベ
- 泊まり込みLT大会とかBBQ大会とか

**Comment by PharaohKJ** [comment]
4/6(Thu)の深夜に打ち合わせしました。

- いまのところ、8人座れる座卓がある以外は、なんにもない
- 駐車場は3台から5台、公共交通機関はナシ
- あんまりおおっぴらでオープンな感じではなく、人の紹介ありきの形でやっているので、公開情報はあんまりなし、対応するのは前向き
- 全てにおいてリクエストベースで対応するので企画があったら打診してください
- 全面的に禁煙

ということでした。meetup時に説明したら close 予定

**Comment by PharaohKJ** [comment]
4/15は盛り上がって説明してないので5月に説明。

**Comment by kiyohara** [comment]
これってもうクローズ？ @PharaohKJ

**Comment by PharaohKJ** [comment]
5月に説明したのでクローズ。
