### ISSUE TITLE
meetup56 買い出し

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#720]
meetup55の運営で話が出来ませんでしたが、・・・・・・
meetup56 Coderetreatという長丁場でお脳に糖が必要です。

当日、開場前に買い出しに行きましょう。
おやつ、飲み物、紙コップ、ウェットティッシュなどの
予算は約3,000円です。(前回予算を参考)
どこで買うかの何も決まってないので、スーパーでも
コンビニでも可です。

前回、付箋やペンって使いましたっけ？
記憶に無いですが、必要であれば100均で買ってきますよ。

----

買い物リストを追記

 * [ ] おやつ
 * [ ] 飲み物
 * [ ] 紙コップ
 * [ ] ウェットティッシュ
 * [ ] 設計の議論用にB4以上のメモパッド（コピー用紙でも可）
      * A4だと2人で使うには小さい
 * [ ] スクウェア強粘着の付箋（強粘着じゃないとすぐ剥がれる） [Amazon | ポスト・イット 強粘着ノート 75x75mm 90枚x5個 蛍光 654-5SSAN | 文房具・オフィス用品 | 文房具・オフィス用品](https://www.amazon.co.jp/gp/product/B002M5F92K)
 * [ ] 付箋に書くためのペン [Amazon.co.jp: ぺんてる:サインペン 10本入　細字(0．8mm) 【インク色:黒】 S520XAD 60023: DIY・工具](https://www.amazon.co.jp/dp/B01BGDM6GU)
     * 書き味と値段から言ってぺんてるの安いやつがサイコー

**Comment by kiyohara** [comment]
武蔵 1F のローソンって、まだ開いてないんだっけ。だとしたらチョット面倒かもね。

**Comment by PharaohKJ** [comment]
近江町だかの地下にお菓子も売ってるドラッグストアあったような、、、。あった。

http://www.simeno.co.jp/k_shop/tenpo_ohumi.html
2017年3月20日(月) 14:19 Tomokazu Kiyohara <notifications@github.com>:

**Comment by TAKAyukiatkwsk** [comment]
> 武蔵 1F のローソンって、まだ開いてないんだっけ

土曜日行ったら開いてましたよー 😃

**Comment by cottondesu** [comment]
エムザB1Fにカジマートある。
http://www.meitetsumza.com/b1f/

買い出しはカジマートかローソン、シメノドラッグ(近江町店)にしましょう。
私一人では持てる量も限られるので、お手伝い可能な方は一緒に買い出しに行きましょう。

**Comment by kiyohara** [comment]
@各位

おおー、結構お店あるんですね。情報ありがとうございます！！
あつまったメンツで、どうするか決めればよさそうね(๑•̀ㅂ•́)و✧

**Comment by cottondesu** [comment]
当日は付箋やペンって使いますか？
必要そうなら事前に100均で購入しようと思うのですが
どうしますか？

**Comment by PharaohKJ** [comment]
在庫持つのも大変だし各自マイツールとして持ってきてね、でいいんじゃないでしょうか。

**Comment by cottondesu** [comment]
各自、付箋を持っていれば持ってきてね！！にしますか？

私自身・・・少ししか手持ちの付箋ないので
これで全員の分を賄うことは無理です。

**Comment by PharaohKJ** [comment]
それでは私がペンと付箋全てを持っていきます。


2017年4月4日(火) 21:05 cottondesu <notifications@github.com>:

**Comment by kiyohara** [comment]
@cottondesu @PharaohKJ そもそも付箋やペンを使うかってところに依存する話なので、 @wtnabe さんの返事を待ちましょう。それで必要とのことでしたら、どうやって準備するか考えましょう。

というわけで @wtnabe さん、当日は付箋やペンに限らず「PC 以外に必要となるもの」がないかご連絡いただけますか？

**Comment by wtnabe** [comment]
@kiyohara @PharaohKJ @cottondesu (@allって使えるんだっけ？)

スマソ。

 * ふりかえりはしたいですね
 * ペンは在庫アリ（昔の金工大 Coderetreat のあまり）
 * 付箋は在庫ナシ

です。

**Comment by kiyohara** [comment]
@wtnabe 

* 「ふりかえり」をやりたいので、ペンと付箋は必要（それ以外に追加で必要なものはない）
* ペンは在庫があるので、 @wtnabe が当日持って行く
* 付箋は在庫がないので、買い出しを検討したい

という解釈であってます？ :p

**Comment by cottondesu** [comment]
微力ながら当日、私が持っている付箋は持っていきますね。

**Comment by kiyohara** [comment]
@cottondesu 付箋は kzrb のキャッシュからまかないましょう。私が領収書付きで買い出してくるので、当日精算してください。
どのぐらい必要かわかりませんが、現状の申し込み具合から10名を想定し、5セットぐらいを買っていくようにします。

もっと買っていった方がいい場合は追加で連絡ください。 > @wtnabe

**Comment by cottondesu** [comment]
@kiyohara はーい、分かりました。
