### ISSUE TITLE
meetup56 レポートを作成する

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#722]
- [x] ツイートまとめ(togetter)
- [x] 写真アルバム(30days)
- [x] レポートページ(github pages)

**Comment by cottondesu** [comment]
togetter: https://togetter.com/li/1101361

30daysの作り方わからなかったので、作成お願いします。

**Comment by izawa** [comment]
30days つくった。
http://30d.jp/kzrb/46
写真を撮っていたかたは、アップロードお願いします。

**Comment by PharaohKJ** [comment]
#723 マージしました。

**Comment by kiyohara** [comment]
30days に写真を追加しておきました :)
