### ISSUE TITLE
GitHubパッチワークの実施

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#731]
2017-06-01に @ikeike443 さんにメールしました。
お返事待ち。

進捗はこちらで報告します。交渉もこちらで相談させてください。

**Comment by bemarble** [comment]
@PharaohKJ 社内で聞いてみたら25人ぐらいGitHubパッチワークに興味ありでした。

**Comment by PharaohKJ** [comment]
うほっ。あざっす。マジすか。 南町勢にも声かけてますが会場がんばらないといけないかな。

**Comment by kiyohara** [comment]
memo:

meetup 58 で状況をシェアし方針を相談した。
事前の声かけでそれなりに人数が集まりそうとの目処がたった。
それを踏まえて、9月に複数コミュニティの共同開催という形で実施する方向で加藤さんに調整してもらっている。
30人以上あつまるのはカタイということで、場所の第一候補は D 社南町オフィス、第二候補は ITBP武蔵の6F。

**Comment by PharaohKJ** [comment]
JAWS-UG金沢は共同でOK。9月第三土曜あたりで調整中とお伝え済み。

**Comment by PharaohKJ** [comment]
おっとしまった、前提として、 @wtnabe さんより、GitHubさまへパッチワーク開催をお願いしたが、
今は受け付けておられませんでした。

しかしながら

- GitHub入門
- GitHub Flow入門

ならば実施できると思うがどうか？とご提案いただけたので検討・調整しているという状況です。

**Comment by wtnabe** [comment]
確認でーす。

@PharaohKJ

「開催されるものはGitHub Patchworkじゃない」ってことでとりあえず合ってますよね？ Patchworkじゃない形式のイベントをやるとして、何か参考になる URL はありませんかね？ 完全に新規のイベントになるんでしょうか？

@bemarble 

多少内容や会場に変更があっても人数の読みに概ね影響なしと見做して大丈夫そうですか？

@kiyohara 

D社開催可否の判明日時とITBP武蔵の予約のデッドがどうなるか、ですね。

※ 参考までに 9/16(土) だと、現時点で

部屋                | 可否
--------------|-----
研修室1 (50人)| NG
交流室1 (82人)| OK
交流室2 (62人)| NG

意外と埋まってたのでちょっと心配になってしまいました。

**Comment by PharaohKJ** [comment]
いまのところ、どのような内容になるのか、どのぐらいの時間がかかるのか、9月第3土曜日でどうでしょうか。
を問い合わせているところです。

会場の担当はおそらく南町の方になると思いますので、そちらと調整進めます。

**Comment by wtnabe** [comment]
@PharaohKJ 前例はないと理解しました。想像を膨らませるのは返事もらってからですね。

**Comment by PharaohKJ** [comment]
内容は

https://speakerdeck.com/ikeike443/being-successful-with-github-1

になるそうです。

ただ、会場名としては問題ありませんが、〜社セミナーとかって形にはできないらしいので、
いろいろと相談が必要になりました。

**Comment by kiyohara** [comment]
@wtnabe ごめんなさい、メンション見落としてた。Slack でも議論が進んでいるけど、場所は要調整な感じですね。本当に人があつまるなら 6F でも良いんじゃない？って気はしている。

**Comment by PharaohKJ** [comment]
先方からご連絡いただきました。

当日新幹線移動となるので13時開始はギリギリになっちゃいそう、ということで14時開始を私から提案しました。
問題ないですよねえ？

加えて、上記の内容だと45分程度だそうです。となると14時-17時？18時？で

- 13時半ごろ開場
- 14時開始
  - GitHub社さまより 45分
  - 休憩
- 15時
  - 会場より 20分
  - Kanazawa.rbより 20分
  - JAWS-UGより 20分
  - 休憩
- 16時すぎより
  - パネルセッション質問大会
- 17時閉場

ぐらいのスケジュールでいこうと考えているのですがどうでしょうか？

**Comment by kiyohara** [comment]
私は、14時スタートにするの、問題ないと思いますよ。

ところで、15時からの枠って TL ですかね？
「会場より」というと、飛び込みでなにか話をするか、という話ですか？

**Comment by PharaohKJ** [comment]
すみませぬ。「会場より」というのは「会場提供社より」のつもりでした。

**Comment by kiyohara** [comment]
なるほど、理解しました :)

**Comment by PharaohKJ** [comment]
9/16(土)、14時より、でGitHub社さまと合意しました。各位よろしくお願いいたします！

**Comment by PharaohKJ** [comment]
- [ ] 8月に入ったら懇親会場を手配する
  - [ ] 先方に食べられないものがないか確認する

**Comment by kiyohara** [comment]
@PharaohKJ 

タイトルと概要って fix してたっけ？
「Github パッチワーク」では、もはやないんだよね？たしか。

**Comment by PharaohKJ** [comment]
GitHub社さまよりのプレゼンは https://github.com/kanazawarb/meetup/issues/731#issuecomment-309646345 にあるとおり https://speakerdeck.com/ikeike443/being-successful-with-github-1 の　Being successful with GitHub　でタイトルはfixだと思うけれど、全体の概要としてはまだかな。

**Comment by PharaohKJ** [comment]
プレゼン担当を決めます。8月前半中には決めたいところ。
重複とか無いように要調整。まずは今月中にネタの提示を各位に求める。
各担当は20分。

- [x] GitHub社さま
- [ ] 会場さま @yu-kgr さんすみませんが手配お願いします。 
  - [ ] プレゼンする人
  - [ ] タイトルと概要
  - [ ] パネルに出る人
- [ ] Kanazawa.rb
  - [ ] プレゼンする人
  - [ ] タイトルと概要
  - [ ] パネルに出る人
- [ ] JAWS-UG 金沢 
  - [ ] プレゼンする人
  - [ ] タイトルと概要
  - [ ] パネルに出る人

**Comment by kiyohara** [comment]
@PharaohKJ GitHub さんの発表に関するタイトル・概要もそうなのだけど、イベント自体のタイトル・概要について確認したかった。そっちはどんな感じでしたっけ。

**Comment by PharaohKJ** [comment]
@kiyohara おっけ。そっちはいつものissueで進めようと考えているのですがいかがか？と思ったらそっちはもうクローズか。

イベント自体のタイトルは前が「Elastic勉強会 in Kanazawa」だったから  「GitHub勉強会 in Kanazawa」でどうでしょうか。概要はちょっと作文します。お待ちを。

**Comment by kiyohara** [comment]
@PharaohKJ 

「GitHub 勉強会 in Kanazawa」 +1

概要対応ありがとう。助かるっす。
しかしまあ、そこまで急ぎじゃないよね。ボチボチ決めましょう。
@yu-kgr サンとの調整もあるでしょうし。jaws 方面もあるでしょうし。。

**Comment by PharaohKJ** [comment]
予定地を作りました

https://connpass.com/event/62218/preview/

@yu-kgr さんと @kiyohara  さんも管理者にしてあるのですが見える？

**Comment by kiyohara** [comment]
@PharaohKJ 見えた :)

**Comment by PharaohKJ** [comment]
食べられないもの > 特になし

**Comment by yu-kgr** [comment]
@PharaohKJ @kiyohara 
すいません、確認おくれました。イベントスペース確認できました！
コチラからの登壇者情報についても情報まとめますね。

**Comment by yu-kgr** [comment]
@PharaohKJ @kiyohara 
社内から一点相談があったんですが、

同日に同じフロアの別の会議室で、
UX関連イベントを開催したいとの要望があがっているんですが、よろしいでしょうか？
※ こちらはオープンスペースでの開催だけどUXイベントの方は別の会議室。

（お互い外部に聞かれたら絶対にダメっていうような内容でもないので、恐らく問題ないかと思うんですが、どちらのイベントに参加される方なのか入り口・受付周りだけ注意する必要がありそうな感じです。）

**Comment by kiyohara** [comment]
@yu-kgr まったく問題ないかと 😄

**Comment by PharaohKJ** [comment]
イベント公開しました。

一般40、懇親会20で計60だったのを確か計40がキャパだったような？と思って合計40になるように変更しておきました。思い違いだったかな？

内容に問題がないか @ikeike443 さまにもメールを送付してチェックを依頼しておきました。

**Comment by PharaohKJ** [comment]
@yu-kgr お盆休みかもしんないからゆっくりでいいけど、盛田さんのプレゼンが私とかぶりそうな感じか確認してもらっていいです？いや、タイトルだけで察してくれというのは酷な話なんですけど。

**Comment by yu-kgr** [comment]
@PharaohKJ 
上記、本人に確認中です〜。
なんとなくCodeDeployで被りそうな気がしている…。

**Comment by yu-kgr** [comment]
@PharaohKJ 
確認した所、
>リリースとデプロイなので、GitHubEnterprise含め他のAWS色々紹介する予定です

との事だったので、加藤さんの `Code` がCodeDeploy周りの話だとしたら被りそうな感じですね。
こちらどうしましょうか？

**Comment by PharaohKJ** [comment]
@yu-kgr 

重複しちゃうけど、そりゃしゃーないかなって感じなんで、私は20分あるのでできればデモ中心にしてみようかなーと考えてます。いったんそんな手分けでいきましょう。

**Comment by yu-kgr** [comment]
@PharaohKJ @kiyohara 
遅れましたが、一般募集が開始されいるので、
弊社の参加希望者の応募も開始しますね。

※ Connpassとは別で30名を上限として募集かけてみます。

**Comment by yu-kgr** [comment]
（合わせて、Connpassの文言をちょっとだけ調整しました。）

**Comment by PharaohKJ** [comment]
@yu-kgr OK。懇親会参加者はconnpass経由で申し込んでいただきたいとお伝え下さい。

**Comment by yu-kgr** [comment]
@PharaohKJ @kiyohara 
>同日に同じフロアの別の会議室で、UX関連イベントを開催したいとの要望
コチラなんですが日程の関係で集客がよろしくなさそうな感じになってしまったとの事で、別日にズレました。
なので、当日は当イベント参加者のみ来る感じになるので受付の複雑化はしないで済みそうです。

**Comment by kiyohara** [comment]
@yu-kgr 承知しましたー :)

**Comment by PharaohKJ** [comment]
ご連絡ありがとうございます。そうなると当日は受付レスでいいかな？

最初の挨拶で飲み会行く人だけ人数確認すれば・・・と思ったけど20人以上もいるから無理か。
ちょっとあとで相談させてください。

**Comment by PharaohKJ** [comment]
@cottondesu さん
connpassで運営担当リクエストするので、当日パソコンでチェックイン受付していただけませんか？

**Comment by kiyohara** [comment]
@PharaohKJ elasticsearchの時は形だけだけど受け付けやったよね。ノベルティがあったというのも理由だと思うけど。。今回ってなにかノベルティとかあるかな。まあ仮にあったとしても「勝手に持って行け」ってスタイルでもいいのだけど。

**Comment by PharaohKJ** [comment]
ノベルティなど、先方に確認しておきます。

**Comment by ikeike443** [comment]
こんにちは。GitHubの池田です。加藤様からメールでも頂いてますが、こちらでも返信しますね。

ノベルティは持っていく予定です。なにかリクエストはありますか？
特になければ、通常は下記を持っていきます。
- ステッカー（大量）
- コースター 数十点
- Octocatフィギュア 数点
- マグカップ 数点
- Tシャツ（ご要望あれば）

なにかアクティビティをやるのであれば、その際の商品として使うこともできますよ

**Comment by PharaohKJ** [comment]
@ikeike443 さん、ご連絡ありがとうございます。

ノベルティありがとうございます！とても楽しみです。

全員に配布できないもの = マグカップ、Octocatフィギュアについては、パネルのお題を出してくれた子に優先的にあげる、というのに使いたいと考えたのですがいかがか？（本会開始時に案内しようと考えています） また他リクエストあれば連絡ください > @kanazawarb/owners

**Comment by kiyohara** [comment]
@ikeike443 ご対応に感謝です。むしろこんなに！？とビックリです。

@PharaohKJ 優先的にあげるというのは良いと思います。司会が少し難しそうだね。パネルの最中には配れないと思うので、イベントの最後に「さっき話をしてくれた人、前に出ろ」とかですかね。当日流れを見ながら考えましょう。

あと、ステッカー等の「全員に配付したい」ものがありそうであることを考えると、やはり受付は受付でやったらいいのでは？と思います。 @cottondesu さんが了承してくれるならよし、ダメそうならまた別途調整しましょう。 :)

**Comment by cottondesu** [comment]
分かりました。当日、受付担当しまーす！！

**Comment by PharaohKJ** [comment]
ありがとうございます。

**Comment by PharaohKJ** [comment]
えんやさんに電話して28+講師1で29人でいったん確定連絡しました。
領収証も対応していただけるとのこと。

**Comment by kiyohara** [comment]
良い感じに実施できた。

最初に動いてくれた @wtnabe さん、とっかかりを作ってくれた @PharaohKJ さんに感謝。
また、当日なにかと動いてくれたメンバーにも感謝。

GitHub 絡みの、またやりたいですね。

**Comment by PharaohKJ** [comment]
滞りなく無事終了いたしました。どうもありがとうございました。

- GitHub使ってて、さらにその運用について勢
- そもそもGitHubとは何か勢

が混ざってしまって、後者が少数すぎて結果として無視する形になってしまったのは反省。（しかも私がそういうところから話しますよ、といって集客してしまった）

近いうちに次回を企画したいという気持ち。

**Comment by ikeike443** [comment]
池田です。先日はありがとうございました！！ すごく楽しかったです！

ところで、私、実はYahoo製のポータブルWifiをどこかでなくしたのですが、もしかしてどなたか会場で見ていたりしないでしょうか？ いつなくしたのかもわからないので、金沢でなくしたのではない可能性も高いのですが、もし万が一それらしいものを見かけたら教えてください。よろしくお願いいたします。

**Comment by PharaohKJ** [comment]
@ikeike443 こちらこそありがとうございました！

会場と飲み屋に連絡してお返事いたします。しばしお待ちを。

**Comment by ikeike443** [comment]
ありがとうございます。お手数おかけします。 🙇

**Comment by kiyohara** [comment]
災難でしたね。

connpass 経由で参加者にも情報共有をお願いしてみます。
会場のほうは @yu-kgr さんに確認をお願いしたく。

情報がでてくるとよいのですが…

**Comment by PharaohKJ** [comment]
@ikeike443 さん、懇親会場、二次会場ともに「忘れ物ありませんでした」とのことでした。

**Comment by ikeike443** [comment]
@PharaohKJ ありがとうございます。実は先程別の場所から見つかった旨連絡がありました。お騒がせしました。ありがとうございます！ 🙇
