### ISSUE TITLE
夏なのでビアガーデン

### ISSUE THREAD

**Issue by cottondesu** [kanazawarb/meetup#732]
kzrbの懇親会でビアガーデン行きたいですよね？

出来れば7月もしくは8月の懇親会で
行きたいなーと思っています。
懇親会費4,000円を超える可能性もありますが、
夏なのではじけましょう！！

ビアガーデンで飲み食べ放題だと候補は以下の3つとなります。

エルビルビアガーデン
男性3,500円/女性3,000円
http://ellebeergarden.com/

ビアガーデン [ハワイアンキング／縁にち]
・180分食べ飲み放題 4,000円
・180分食べ飲み放題 + チキンステーキとスペアリブ二種盛り 5,000円
https://kanazawa-beergarden.com/

ANAクラウンプラザ ビアテラス
大人6,000円
http://www.anacrowneplaza-kanazawa.jp/rest/beer/

本issueでいつ、どのお店に行くのかを検討したいと思います。
上記以外のビアガーデンやビアホールで行きたいところがあれば
教えてください。

**Comment by PharaohKJ** [comment]
どこも金・土・祝は90分か100分になっちゃうんだなあ。エルビルに一票。

**Comment by kiyohara** [comment]
行きたいね。俺もエルビルに一票かな。

※フォーラスの上は、やめたほうがいい（遠い目

**Comment by cottondesu** [comment]
明日まで様子を見て反対意見等がなければ、
7/15 meetup59の懇親会のお店として
エルビルに電話してみます。

**Comment by TAKAyukiatkwsk** [comment]
エルビルお手ごろでよさげですね 🍻 （サイト開いたら音声流れてきて驚いた...w）

**Comment by cottondesu** [comment]
7/15 17:30でエルビルビアガーデンを仮10名で予約しました。
人数変更は前日までで、料金(男性3,500円/女性3,000円)は前払い制とのことです。

**Comment by kiyohara** [comment]
@cottondesu 
meetup 59 の申し込みページを作っていたのだけど、上記って税別かな？
具体的には懇親会費用を3500円にしておくか4000円にしておくか、的な話なのだけど。

**Comment by cottondesu** [comment]
@kiyohara 
料金(男性3,500円/女性3,000円)は税込です。
エルビルビアガーデンのHP上にあるCM動画を見ると
税込と記載ありました。

**Comment by kiyohara** [comment]
👍

**Comment by kiyohara** [comment]
Issue としてはクローズとの認識。
必要あれば re-open お願いしまーす。

**Comment by cottondesu** [comment]
お店に連絡して、懇親会の参加人数を4名に変更しました。

**Comment by kiyohara** [comment]
おっと、申し訳ない。最後の人数調整というタスクがありましたね。
先走ってクローズしてしまってもうしわけなし…
