### ISSUE TITLE
Doorkeeper フォトギャラリー機能の評価

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#761]
フォトギャラリー機能というのがついたそうです。

http://support.doorkeeper.jp/article/122-photo-gallery

現在は 30days に写真をあげています。
メリットがあるなら乗り換えるのもありかなと。
変更した方がよいのかどうか、っていうところから考えないといけませんが。

コメントがあれば是非に。

**Comment by kiyohara** [comment]
サンプルとしてはこちら。
これはコミュニティページに設定されてますが、イベントページにも設定できるみたいですよ。

https://trbmeetup.doorkeeper.jp/

**Comment by kiyohara** [comment]
ん？あれ、イベントページには設定できないかも…
「コミュニティの管理」のところしか「フォトギャラリー」ってリンクないなあ。
勘違いかもしれないです。もうちょっと調べてから追加で報告します。五月雨になって申し訳ない。

**Comment by TAKAyukiatkwsk** [comment]
> フォトギャラリーに追加できる写真は100枚までです。

とのことなので現状のような各々がアップする使い方だとすぐに埋まってしまいそうですね😅

**Comment by kiyohara** [comment]
と言うわけで追加でいろいろ調べましたが、やはりイベント毎に作られるものではなく、コミュニティ全体のページに設定出来るもののようです。
30 days を置き換えるものではないですね。

コミュニティページに設定できるのは、設定しておけばよいと思います。
どこかの meetup の運営ブレストあたりで写真選定大会でもやりましょう :)
別途 Issue をたてます
