### ISSUE TITLE
21世紀美術館イベントスペースでの開催検討

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#786]
GitHub勉強会会場で営業かけられたので調査します。

結果をkzrb本会で報告したらクローズ予定。

**Comment by PharaohKJ** [comment]
現在、会場仕様をヒアリング中。

**Comment by PharaohKJ** [comment]
21美担当のかたをご紹介いただいたので、メール送付、アポ依頼中。

https://github.com/kanazawarb/meetup/wiki/%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E9%96%8B%E5%82%AC%E5%A0%B4%E6%89%80%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%83%AA%E3%82%B9%E3%83%88

にそってお話できないか依頼した。（短縮URL作成しました → http://bit.ly/kzrbeventspace )

**Comment by kiyohara** [comment]
運用ブレストで情報展開実施済み。

運用ブレストログ ( https://github.com/kanazawarb/meetup/wiki/meetup-63-%E9%81%8B%E7%94%A8%E3%83%96%E3%83%AC%E3%82%B9%E3%83%88%E3%83%AD%E3%82%B0 )

結論としては、直近のコラボは難しそう。
21世紀美術館の期待するイベントを企画できそうな場合に声かけすることとした。

「直近については」 @PharaohKJ さんからお断りの連絡を入れる。

**Comment by PharaohKJ** [comment]
見合わせますメールしました。
