### ISSUE TITLE
meetup ページのサブドメイン化検討

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#877]
現在 kzrb.org/meetup とサブディレクトリで運用されている meetup ページを meetup.kzrb.org とサブドメイン化して運用出来ないかを検討したい。
主たるモチベーションは netlify を導入する事によって今よりも簡単にレビュー環境を構築すること。

なお、過去に作成したリンクが失われないようにする仕組みが存在することは確認済み
kzrb.org/meetup/*.* を meetup.kzrb.org/*.* にリダイレクトするような仕組み。
リダイレクトなので影響がゼロとは言えないが…

また、現在のような構成となっている意図も @wtnabe さんに確認済み。
サブプロジェクトのようなものが複数立ち上がり、それぞれのプロダクトページがサブディレクトリとして /meetup と並列に並ぶことを想定していたとのこと。
kanazawarb.github.io というドメイン配下で動作させる GitHub が想定する構成においては、当然そうなるよね、という話。

kzrb.org を保持して、サブドメインを切ることができるようになったことで選択肢が広がっているとの認識。
プロダクトページを GitHub Pages 以外、それぞれに好きなものをもちいることができるというメリットと、 kzrb.org というドメイン保持・運用のコスト（および /meetup の URL 変更）というデメリットとの天秤という話に集約できそう。

---

ご意見のある方は是非本 Issue にコメントください。
可能であれば meetup 70 の運用ブレストでおおよその方針決めと同意を得たいと思ってます。

**Comment by izawa** [comment]
meetupの運営議事で賛成多数を得たので、進める方向で動いてよしとなった。

**Comment by kiyohara** [comment]
@izawa 取りまとめ、ありがとうございますー。Go とのことですので、なんやイイガニしてみますー。

サブドメイン化については合意との認識なので本 Issue はクローズします。

netlify への移行に向けた作業は、それはそれ別途 Issue 立てますね。
