### ISSUE TITLE
運営 role における expire 設定

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#878]
Kanazawa.rb は、基本的には全員運営を目標としているので、運営者権限といったものは存在しません。
誰でも「手伝うよ」と手を上げてくれれば基本無条件で GitHub の管理者権限を付与したり Dropbox のシェアディレクトリといったものに参加できるようにしています。（というのが @kiyohara の認識だけど、違ってたら指摘して下さい。おもに @wtnabe さん。）

一方で、状況の変化によって「お手伝いがしにくくなる」こともあるだろうなと感じています。
そんな人達に向けて GitHub から Access Key のパーミッションがどうだとかのメールが飛ぶのは忍びない、という気持ち。

なので、なんらかの条件に当該する方には、いったんその手の管理者設定を外すのがよいのでは、と考えているのですがコメントいただけませんか。

条件のたたき台は以下の通りです。

* 以下、すべての条件を満たす人
  * 1年以上 meetup に参加していない
  * 1年以上 github issue もしくは slack 上でのやりとりがない
  * こちらからお手伝いを継続してもらえるかを問い合わせ、30日以内に応答がない

当然、管理者設定を外しても再度手を上げてもらえれば無条件で再設定する、という前提で考えています。
こちらも、可能であれば meetup 70 で方針決めと同意が得られると嬉しいなあ :)

**Comment by izawa** [comment]
「六ヶ月なり一年なりで、「自動的に」全員がexpireするという仕組みのほうが、フェアーなきがする、改めて、手伝う意志を示した人に権限を与える方針はどうだろうか。」

という意見が出た。

**Comment by kiyohara** [comment]
なるほど、それもありですね。
私としても全員 expire モデルでもよいように思います。

・更新意思確認のスキームをなんらか設定すること
・（運用が変わることに伴って）今、運営 role を持っている人には説明をすること

このあたりだけ押さえておく必要はありそうですね。

「意見が出た」とのことで、まだ実際に施行しようというほどの段階ではない、との認識。
次回 meetup 71 で継続検討ですかね :)

**Comment by kiyohara** [comment]
https://github.com/kanazawarb/meetup/wiki/%E9%81%8B%E5%96%B6%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6#%E5%8F%82%E5%8A%A0%E6%96%B9%E6%B3%95%E3%81%A8%E6%9C%9F%E9%99%90%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

いったん上記にまとめた
