### ISSUE TITLE
kzrb.org の Netlify 化対応

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#884]
meetup.kzrb.org を netlify で運用する。

- [x] コンテンツの移行
- [x] 旧 URL に対するリダイレクト設定
- [x] 内容更新手順のまとめ

※現行の /meetup というサブディレクトリ構成を meetup.kzrb.org のサブドメイン化する点については #877 で合意済み。

**Comment by kiyohara** [comment]
## Netlify へのデプロイについて
Netlify への以降は完了
手順のまとめについては、事実上いらなかった（今まで通り PR を出してマージでOK ）

1点だけ、設定 ( https://github.com/kanazawarb/meetup/settings/branches ) からデフォルトブランチを `gh-page` から `master` に変更してある点はご留意の程。
（普通は `master` だけど、変更されてた。たぶん、 @wtnabe さんが本リポジトリの使い方を鑑み、意図的に設定してくださったのだと思う）

## サブドメイン化について

`https://kzrb.org/meetup` を `https://meetup.kzrb.org` というサブドメインにする点についても対応済み。
`https://kzrb.org/meetup/{{num}}/` は `https://meetup.kzrb.org/{{num}}/` にリダイレクトされるようになっている。

## gh-pages について
`https://kanazawarb.github.io/` および `https://kanazawarb.github.io/meetup/` は引き続き github pages で提供継続されている。
注意点として、内容が最新化されない状況にある点は留意。（ `master` → Netlify で `gh-pages` → github pages となっており、 `master` の更新と `gh-pages` の更新は分離している状態）

gh-pages を disable しておくのか、 gh-pages も最新に追従するように仕組み自体を整えるという二択があるので、これは引き続き検討したいところ。

- [ ] gh-pages をどう運用するかについて方針をたてる

**Comment by kiyohara** [comment]
Github desc が github pages の URL だったものを kzrb.org に向けた。
gh-pages は復旧も簡単なので、いったん削除して必要が出たら戻ってくる運用とさせてもらいたい。

**Comment by muryoimpl** [comment]
こちら手順化作業はいかがでしょうか？
一旦、PR で preview が見えるということで Netlify 便利〜となっているので、gh-pages に戻ることはなさそうと思っています。

権限も絡むので手順化とその公開が難しい…とかそういうのであれば、一旦クローズする、もしくは、手順化だけ仕切り直すのもありかと思うのですが、いかがでしょう？

**Comment by kiyohara** [comment]
キックありがとうございます！！

「内容更新手順のまとめ」としていた sub task は

> 手順のまとめについては、事実上いらなかった（今まで通り PR を出してマージでOK ）

ということで、対応不要でした。
対応不要の場合、✓ 入れるのか？って悩んで未チェックだったんですが、対応完了ということで、✓入れるべきでしたね 😓 


「gh-pages をどう運用するかについて方針をたてる」としていた sub task が open だったのですが、重い腰をあげて全部 kzrb.org にリダイレクトする設定をいれました。
いろいろ手段はあるのですが、 CNAME 方式で。

ref. https://blog.atusy.net/2019/03/11/use-cname-to-redirect-from-gh-pages/

gh-pages ブランチはそのファイルのみ残っている形になっています。
Orphan にすればすっきりするんでしょうが、 <s>めんどくさかったので</s> 過去の gh-pages から切りました 😅 
github pages の設定画面では、github に向いてないぞって怒られてますが、パスまわりを維持したままリダイレクトされる設定は残っています。
これで、過去に公開した kanazawarb.github.io へのリンクは活きたままになるかと。

と言うわけで本 issue はクローズできるかと。
この後 slack でもアナウンスしていきます。
