### ISSUE TITLE
大型勉強会企画

### ISSUE THREAD

**Issue by PharaohKJ** [kanazawarb/meetup#923]
Terraform で有名？な HashiCorp さんと Google Cloud Next 2018 で名刺交換しました。

別勉強会でも興味ある内容なので、大型勉強会として企画できないでしょうか？

先方も調整次第OKとおっしゃってらっしゃるので詰めていこうと考えています。どうでしょう？
次会で興味あるかないか、含めてお話したいです。

**Comment by kiyohara** [comment]
面白い話だと思うし、ポジティブサイドということを表明。
ちなみに、どういった内容で話してもらうかも含めて調整中との認識であってますよね？

**Comment by PharaohKJ** [comment]
いえす。

**Comment by kiyohara** [comment]
ya

**Comment by PharaohKJ** [comment]
Terraform Enterprise & Vault ネタ、3月でどうか？と先方からお返事いただけました。

会場予定地と他団体それぞれ調整をしていきます。 スケ的には meetup 79 かな。3/16 かな。

**Comment by yu-kgr** [comment]
@kiyohara @PharaohKJ 
南町の施設利用の申請にあたり、朝日生命ビルに下記の情報を送る必要があります。
つきましては、こちらの内容について確認させて頂けないでしょうか？
※ 尚、こちらは協賛であるとビルに報告します

```
- 開催日時 : 
- イベント名 : （例） : HashiCorp勉強会  ※仮で大丈夫です
- 参加者 : 約xx名程度
- 来訪者詳細 : ◯◯社　✕✕様
- 映像・写真撮影の有無 : 有 / 無 （SNSへのアップ程度であればなしで問題ないです）
```

また、要事前申請（掲示物の事前提出含め）ではありますが、
ビル1Fエントランスホール壁際と9Fエレベータホール前にA4二枚サイズの立て看板を設置することが可能です。こちら利用など行いますか？

**Comment by yu-kgr** [comment]
適切な記載場所がわからないので、
一旦こちらにおやくそく的なものを記載しておきます。

```
▼ 写真撮影に関するお願い
参加者に対しては「SNSに写真を上げる際は、ビル外観はNGで、ビルの場所と他のテナントが特定できないように」という周知をお願いします。

理由は「ビルへ入居している企業の意図せぬ住所流出を防ぎ、またその企業へ出入りしている人員の個人情報保護のため（こちらは表記しませんが）」です。
```

**Comment by yu-kgr** [comment]
また、可動式のHDMIモニターを利用する事も可能です。
リアルタイムでTwitterTLの表示やQAなどを表示させたいなどあれば、事前に伝えていただければと思いますー

**Comment by kiyohara** [comment]
朝日生命ビルに向けての情報は @PharaohKJ さんに取りまとめてもらうのが良さそうですね。
写真に関しては承知しました。参加者への周知という点で留意しておくようにいたします。

**Comment by yu-kgr** [comment]
### 施設予約ステータス 

- 社内での頭出し完了
- 朝日生命ビルに対して提出する情報待ち
    - @PharaohKJ さんボール

#### 残りのアクション

- 朝日生命ビルに対する情報提出
- （Optional）掲示物周りの手配
- （Optional）可動式HDMIディスプレイの手配

**Comment by yu-kgr** [comment]
こちら、利用する1ヶ月前にて提出せなあかんのでよしなによろしくおねがいしますー

**Comment by PharaohKJ** [comment]
来週月曜先方とテレカンファレンスなんでそれまでまってくれ

**Comment by PharaohKJ** [comment]
# HashiCorpさま 打ち合わせ

- 日時について
  - 3/16 14:00ごろ〜18:00、から懇親会
- 会場について
  - 金沢、南町でOK
- 表記について
  - HashiCorp さま 会社名・商品名を勉強会タイトル・イベントツールで使用可
- 内容について
  - オープニング：各位紹介とディスカッション時の質問募集
  - 前半：HashiCorp 伊藤さま より 製品(enterprise版、OSSとの違い、マルチクラウドなど)について (1時間ほど)
  - 中盤：10分 x 3 本ほど各コミュニティより HashiCorp さんの製品が解決しようとしてる課題や製品自体についてプレゼン
  - 中休み：(長め)
  - 伊藤さま x 登壇者によるディスカッション
  - (18:00終了)
  - 懇親会
- 確認事項
  - OSS版の質問は答えられないことがあるかも
    - たぶんそこまで突っ込んで質問されることはないはず
  - 伊藤さんに話ていただきたい内容については各コミュニティに @PharaohKJ  からヒアリングしておき、あったらメールでまとめて連絡する
  - 準備など進捗あったら @PharaohKJ  からメールで連絡する

**Comment by PharaohKJ** [comment]
会場手配開始します

**Comment by yu-kgr** [comment]
情報を元に、D社南町へ申請しました。
D社内は承認済みで、残りはビル管理会社の承認待ちのステータスです。

**Comment by PharaohKJ** [comment]
https://connpass.com/event/120462/preview/

@yu-kgr @kiyohara ↑の記載で内容に間違いがないか確認してください。先日の勉強会のやつからコピーで作ったのですが、時間もたってるので社名表記やアナウンスに間違いがないかチェックお願いします。

OK次第公開します。

**Comment by kiyohara** [comment]
@PharaohKJ おおよそ問題ないかと。
以下の2点だけ気になったので調整しておきました。

* スケジュール部分の「GitHubについてパネルセッションと質問会」との記載を「パネルセッションと質問会」に変更
* 全体的に「未定」との記載を「調整中」に変更

**Comment by yu-kgr** [comment]
@PharaohKJ 
確認いたしました。下記の点だけ修正をお願いします。

>運営にはDMM .com Laboさま、Kanazawa.rbさま、JAWS-UG金沢さまのご協力を得ています。

DMM .com Labo => 合同会社 DMM .com に変更をお願いします。


>プラットフォーム事業本部 メンバーシップサービス部 アカウントスクラムチーム - 井上一也 さま
>プラットフォーム事業本部 メンバーシップサービス部 カスタマーサービスサポートチーム - 加茂野真冬 さま

合同会社 DMM.com プラットフォーム事業本部 ... という形に変更をお願いします。

**Comment by yu-kgr** [comment]
あ、自分のほうでも変更可能でした。
変更しておきます。

**Comment by PharaohKJ** [comment]
@yu-kgr 右中段ぐらいにある「会場」についてはどうですかね？

**Comment by yu-kgr** [comment]
@PharaohKJ 
あ、本当ですね。ありがとうございます。
こちらも変更しておきます

**Comment by PharaohKJ** [comment]
@yu-kgr  確認しました。ありがとうございます。 JAWS-UG金沢側 OK 出次第、公開いたします。

**Comment by PharaohKJ** [comment]
みなさんのおかげで準備滞りなく進んでおります。

イベントページの表記などについてはいまのところ講師確認待ちで、2/18(月) に電話して確認とる予定です
[connpass](https://connpass.com/event/120462/)

当日土曜日の

- 受付担当
- 会場ビル入口から会場への案内員
- 会場内施設案内
- 会場内登壇者ら各種接続確認
- kzrb 側登壇者
- kzrb 側ディスカッション登壇者

を手伝ってほしいです。できれば本日の kzrb 会にて担当決めていただきたい（ビル外には私が立つ予定です、
JAWS-UG金沢からも手配する予定で、更新あればここで連絡します）

@yu-kgr さん、承認待ちなどステータス変更あったらまた連絡ください

**Comment by kiyohara** [comment]
@PharaohKJ 
Kanazawa.rb 側の発表者（ディスカッション含む）は @muryoimpl さんが手をあげてくれた。
発表順番はもう少し早いほうがいいな、とのこと

その他スタッフとして、 @cottondesu @kkabetani さんのお二人が手をあげてくれた。

細かな調整については Slack 等でやりとりしつつ詰められれば、とのこと。

**Comment by kkabetani** [comment]
予定大丈夫だったのでお手伝い可能です。

**Comment by yu-kgr** [comment]
@PharaohKJ 
>承認待ちなどステータス変更あったらまた連絡ください
ビル側の承認については、問題があれば連絡が来るという形で、
問題がなければ何も連絡がこないとの事です。

現時点では連絡が着ておりませんので問題ないかと思います。

**Comment by yu-kgr** [comment]
9F許可、特に問題なさそうですので施錠用のキーを本日受け取る予定です。
（今回はビアバッシュと聞いていないので8Fは利用しない予定ですが問題ないですよね？）

**Comment by PharaohKJ** [comment]
ビアバッシュ？使うと8F使うの？それすらわからん・・・ごめん。
前回のGitHubの会でお借りした会場のつもりでした。

**Comment by yu-kgr** [comment]
>ビアバッシュ？使うと8F使う
8Fは従業員用の冷蔵庫があるので、ビールを冷やす用途のためだけに8Fも利用していた感じです。

**Comment by PharaohKJ** [comment]
うほっ。なるほどそれいいね！今回は使いません。ありがとう。

**Comment by yu-kgr** [comment]
@PharaohKJ 
LT登壇者の加茂野よりLTのタイトルを「Terraformについて」から「Orbsから始めるTerraform生活」に変更依頼が来たので、変更しておきます。

また、事前にLT資料を公開しておきたいみたいなのですが、
connpassのほうに展開しても大丈夫でしょうか？

**Comment by PharaohKJ** [comment]
@yu-kgr 
ok ぜひよろしくです。

**Comment by kiyohara** [comment]
@PharaohKJ @cottondesu 先生のご尽力によりレポートページ ( https://meetup.kzrb.org/79/report.html ) 公開になっているので、各所連絡にご利用ください。
いいイベントになりましたね。

残件なくなり次第、適宜クローズください :)

**Comment by PharaohKJ** [comment]
無事終了。各位感謝。レポート送付します。クローズ。
