### ISSUE TITLE
運用グループドキュメントを完成させる

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#933]
https://github.com/kanazawarb/meetup/wiki/%E9%81%8B%E5%96%B6%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

2018/10/20 の meetup でたたき台を作成。
同日にレビューを実施した分は反映済み。

さらに、以下について追加済み。

* Doorkeeper の管理者にかかる記載
* 強制的な排除に至る条件を記載

追加のコメントを是非いただきたく。
逆に、問題なしとの場合は 👍 をください。

**Comment by izawa** [comment]
:+1:

**Comment by kiyohara** [comment]
いったん上記内容で fix としてます。
当然、追加のコメントは受け付けておりますので、 Slack あたりでいつでもご指摘下さい :)
