### ISSUE TITLE
meetup76 ビアバッシュ向け事前買い出しチームの調整

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#948]
以下、留意事項

* 各自に自分の「飲み物」を持ってくるようにアナウンスしている
* 今回もオンデマンドピザ発注&バイク追跡を行う予定
* その上で、イベント前に乾き物や予備の飲みのを購入しておく
  + 飲み物は DMM さんの冷蔵庫を利用させてもらえる、と思う
    - [x] 要確認

**Comment by yu-kgr** [comment]
>冷蔵庫を利用
前回と同様に8F冷蔵庫を利用させてもらえないかを南町総務に確認中。
返答が来たら改めてご報告します。

**Comment by kiyohara** [comment]
@yu-kgr ありがとうございます。助かります 🙇

**Comment by kiyohara** [comment]
@yu-kgr 確認ありがとうございます！是非使わせていただきたく。
容量的にはどの程度はいりますかね？

**Comment by yu-kgr** [comment]
@kiyohara 
このようなタイプの冷蔵なので、いれるもの形状によりますが20-30本程度の缶ははいるかと思います。
![image](https://user-images.githubusercontent.com/6540072/49058880-4ccf7980-f249-11e8-8ee8-f14bbc8e0011.png)

**Comment by kiyohara** [comment]
@yu-kgr おお！詳細な情報ありがとうございます 😉  参考にさせていただきます！
