### ISSUE TITLE
meetupページのデザインを最適化したい

### ISSUE THREAD

**Issue by yu-kgr** [kanazawarb/meetup#950]

**Comment by yu-kgr** [comment]
勝手にシコシコ進めたいと思うので、logoがほしい所存でございます🤩

**Comment by kiyohara** [comment]
@yu-kgr 

![logo_kzrb_biggest](https://user-images.githubusercontent.com/340621/50062492-ccb68700-01ea-11e9-94b5-86670f06c9d0.png)

こちらでいかがでしょう！

**Comment by yu-kgr** [comment]
ありがとうございます！完璧です

**Comment by yu-kgr** [comment]
（そういえば…まだ途中でほったらかしてましたけどこんな感じでちょくちょく進めてたりします…）

![image](https://user-images.githubusercontent.com/6540072/107210692-d98c3980-6a47-11eb-8d34-71ca414944da.png)

**Comment by kiyohara** [comment]
オッ、いいっすね！
この辺、現在のデザインを立ち上げてくれた @wtnabe さんのコメントも欲しいとこですよね！ 😉

**Comment by yu-kgr** [comment]
（一応、当時のwtnabe先生からは勝手に YOU 勝手にやっちゃいなYO って言われたのでなんかいい感じにしたら、PR飛ばしますね！みたいな事いってました）

**Comment by yu-kgr** [comment]
`IMO`

コンテンツ精査

- /slides.html - 2014年以降は運用されていなさそうなので作事をしてもよさそう？
- /howto-make-meetup.html - あえて記載せずとも各募集ページなどにも記載されているので大丈夫そう？

---

一旦、FigmaでUIを作成完了。
問題なさそうであればJekyllのtheme化する動きを見せたいと思います。

https://www.figma.com/file/j8rbJqMDV1iLF4U6oeBpGD/kzrb?node-id=0%3A1

**Comment by muryoimpl** [comment]
双方にとっての呪縛になっていないか、やると待つでデッドロックになっていないかが気になっています。
最後の更新から 1.5年が経とうとしているので、一旦クローズして楽になりましょう。機運が高まったら re-open で。

meetup の元になったデザインはおそらく https://pages-themes.github.io/dinky/ だと思うので、meetup#120 に向けてちょっとした目先の対応みたいなものをやってみようと私は考えています。
最適化とまではいかんものの、左のメニューが長くなってしまっているとか、スマホで見づらいとかは解消したい…
