### ISSUE TITLE
Google+ へのポスト終了

### ISSUE THREAD

**Issue by kiyohara** [kanazawarb/meetup#976]
あと数ヶ月さき、2019年4月に終了されるとされている Google+ へのアナウンス（イベント開催告知 & イベントレポート告知）を、 meetup 77 のレポート通知から終了としたいです。
通知に利用していた Buffer が本日 2019/01/25 から Google+ のサポートを打ち切ったのが契機です。

OK してくれるかたは 👍 ください。
👍  が私を除いて 5 件得られたら承認としたく。

**Comment by izawa** [comment]
👍

**Comment by yu-kgr** [comment]
👍👍

**Comment by kiyohara** [comment]
（ひとりで :+1: ２つ突っ込んでくるという新しい概念に戸惑っている（カウント1やで！

**Comment by PharaohKJ** [comment]
:+1:

**Comment by kiyohara** [comment]
5件いただけたので、本件承認ということでクローズします。
Google+ に以降の更新は実施しない点、ポストしておきます。

**Comment by kiyohara** [comment]
ref. https://plus.google.com/b/112019730992271991381/+KzrbOrg/posts/eW7zQRzxHiE
